//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Neosinerji.BABOnlineTP.Business.allianz {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GenericProcessExecutorPortBinding", Namespace="gs.az.tr")]
    public partial class GenericProcessExecutorService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback executeOperationCompleted;
        
        private System.Threading.SendOrPostCallback listProcessDescriptorsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getProcessDescriptorOperationCompleted;
        
        private System.Threading.SendOrPostCallback getObjectDescriptorOperationCompleted;
        
        private System.Threading.SendOrPostCallback setConlog_idOperationCompleted;
        
        private System.Threading.SendOrPostCallback getConlog_idOperationCompleted;
        
        private System.Threading.SendOrPostCallback getValueSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDisabledOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVisibleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GenericProcessExecutorService() {
            this.Url = global::Neosinerji.BABOnlineTP.Business.Properties.Settings.Default.Neosinerji_BABOnlineTP_Business_allianz_GenericProcessExecutorService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event executeCompletedEventHandler executeCompleted;
        
        /// <remarks/>
        public event listProcessDescriptorsCompletedEventHandler listProcessDescriptorsCompleted;
        
        /// <remarks/>
        public event getProcessDescriptorCompletedEventHandler getProcessDescriptorCompleted;
        
        /// <remarks/>
        public event getObjectDescriptorCompletedEventHandler getObjectDescriptorCompleted;
        
        /// <remarks/>
        public event setConlog_idCompletedEventHandler setConlog_idCompleted;
        
        /// <remarks/>
        public event getConlog_idCompletedEventHandler getConlog_idCompleted;
        
        /// <remarks/>
        public event getValueSetCompletedEventHandler getValueSetCompleted;
        
        /// <remarks/>
        public event getDisabledCompletedEventHandler getDisabledCompleted;
        
        /// <remarks/>
        public event getVisibleCompletedEventHandler getVisibleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="gs.az.tr", ResponseNamespace="gs.az.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public serviceCommandResult execute([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] serviceCommand arg0) {
            object[] results = this.Invoke("execute", new object[] {
                        arg0});
            return ((serviceCommandResult)(results[0]));
        }
        
        /// <remarks/>
        public void executeAsync(serviceCommand arg0) {
            this.executeAsync(arg0, null);
        }
        
        /// <remarks/>
        public void executeAsync(serviceCommand arg0, object userState) {
            if ((this.executeOperationCompleted == null)) {
                this.executeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexecuteOperationCompleted);
            }
            this.InvokeAsync("execute", new object[] {
                        arg0}, this.executeOperationCompleted, userState);
        }
        
        private void OnexecuteOperationCompleted(object arg) {
            if ((this.executeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.executeCompleted(this, new executeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="gs.az.tr", ResponseNamespace="gs.az.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public processDescriptor[] listProcessDescriptors([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("listProcessDescriptors", new object[] {
                        arg0});
            return ((processDescriptor[])(results[0]));
        }
        
        /// <remarks/>
        public void listProcessDescriptorsAsync(string arg0) {
            this.listProcessDescriptorsAsync(arg0, null);
        }
        
        /// <remarks/>
        public void listProcessDescriptorsAsync(string arg0, object userState) {
            if ((this.listProcessDescriptorsOperationCompleted == null)) {
                this.listProcessDescriptorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistProcessDescriptorsOperationCompleted);
            }
            this.InvokeAsync("listProcessDescriptors", new object[] {
                        arg0}, this.listProcessDescriptorsOperationCompleted, userState);
        }
        
        private void OnlistProcessDescriptorsOperationCompleted(object arg) {
            if ((this.listProcessDescriptorsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listProcessDescriptorsCompleted(this, new listProcessDescriptorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="gs.az.tr", ResponseNamespace="gs.az.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public processDescriptor getProcessDescriptor([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("getProcessDescriptor", new object[] {
                        arg0});
            return ((processDescriptor)(results[0]));
        }
        
        /// <remarks/>
        public void getProcessDescriptorAsync(string arg0) {
            this.getProcessDescriptorAsync(arg0, null);
        }
        
        /// <remarks/>
        public void getProcessDescriptorAsync(string arg0, object userState) {
            if ((this.getProcessDescriptorOperationCompleted == null)) {
                this.getProcessDescriptorOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetProcessDescriptorOperationCompleted);
            }
            this.InvokeAsync("getProcessDescriptor", new object[] {
                        arg0}, this.getProcessDescriptorOperationCompleted, userState);
        }
        
        private void OngetProcessDescriptorOperationCompleted(object arg) {
            if ((this.getProcessDescriptorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getProcessDescriptorCompleted(this, new getProcessDescriptorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="gs.az.tr", ResponseNamespace="gs.az.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public objectDescriptor getObjectDescriptor([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("getObjectDescriptor", new object[] {
                        arg0});
            return ((objectDescriptor)(results[0]));
        }
        
        /// <remarks/>
        public void getObjectDescriptorAsync(string arg0) {
            this.getObjectDescriptorAsync(arg0, null);
        }
        
        /// <remarks/>
        public void getObjectDescriptorAsync(string arg0, object userState) {
            if ((this.getObjectDescriptorOperationCompleted == null)) {
                this.getObjectDescriptorOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetObjectDescriptorOperationCompleted);
            }
            this.InvokeAsync("getObjectDescriptor", new object[] {
                        arg0}, this.getObjectDescriptorOperationCompleted, userState);
        }
        
        private void OngetObjectDescriptorOperationCompleted(object arg) {
            if ((this.getObjectDescriptorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getObjectDescriptorCompleted(this, new getObjectDescriptorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="gs.az.tr", ResponseNamespace="gs.az.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setConlog_id([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            this.Invoke("setConlog_id", new object[] {
                        arg0});
        }
        
        /// <remarks/>
        public void setConlog_idAsync(string arg0) {
            this.setConlog_idAsync(arg0, null);
        }
        
        /// <remarks/>
        public void setConlog_idAsync(string arg0, object userState) {
            if ((this.setConlog_idOperationCompleted == null)) {
                this.setConlog_idOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetConlog_idOperationCompleted);
            }
            this.InvokeAsync("setConlog_id", new object[] {
                        arg0}, this.setConlog_idOperationCompleted, userState);
        }
        
        private void OnsetConlog_idOperationCompleted(object arg) {
            if ((this.setConlog_idCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setConlog_idCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="gs.az.tr", ResponseNamespace="gs.az.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getConlog_id() {
            object[] results = this.Invoke("getConlog_id", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getConlog_idAsync() {
            this.getConlog_idAsync(null);
        }
        
        /// <remarks/>
        public void getConlog_idAsync(object userState) {
            if ((this.getConlog_idOperationCompleted == null)) {
                this.getConlog_idOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetConlog_idOperationCompleted);
            }
            this.InvokeAsync("getConlog_id", new object[0], this.getConlog_idOperationCompleted, userState);
        }
        
        private void OngetConlog_idOperationCompleted(object arg) {
            if ((this.getConlog_idCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getConlog_idCompleted(this, new getConlog_idCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="gs.az.tr", ResponseNamespace="gs.az.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public valueSet getValueSet([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] field arg2, [System.Xml.Serialization.XmlElementAttribute("arg3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] field[] arg3) {
            object[] results = this.Invoke("getValueSet", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3});
            return ((valueSet)(results[0]));
        }
        
        /// <remarks/>
        public void getValueSetAsync(string arg0, string arg1, field arg2, field[] arg3) {
            this.getValueSetAsync(arg0, arg1, arg2, arg3, null);
        }
        
        /// <remarks/>
        public void getValueSetAsync(string arg0, string arg1, field arg2, field[] arg3, object userState) {
            if ((this.getValueSetOperationCompleted == null)) {
                this.getValueSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetValueSetOperationCompleted);
            }
            this.InvokeAsync("getValueSet", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3}, this.getValueSetOperationCompleted, userState);
        }
        
        private void OngetValueSetOperationCompleted(object arg) {
            if ((this.getValueSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getValueSetCompleted(this, new getValueSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="gs.az.tr", ResponseNamespace="gs.az.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getDisabled([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] field arg2, [System.Xml.Serialization.XmlElementAttribute("arg3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] field[] arg3, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out bool @return, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] out bool returnSpecified) {
            object[] results = this.Invoke("getDisabled", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3});
            @return = ((bool)(results[0]));
            returnSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void getDisabledAsync(string arg0, string arg1, field arg2, field[] arg3) {
            this.getDisabledAsync(arg0, arg1, arg2, arg3, null);
        }
        
        /// <remarks/>
        public void getDisabledAsync(string arg0, string arg1, field arg2, field[] arg3, object userState) {
            if ((this.getDisabledOperationCompleted == null)) {
                this.getDisabledOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDisabledOperationCompleted);
            }
            this.InvokeAsync("getDisabled", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3}, this.getDisabledOperationCompleted, userState);
        }
        
        private void OngetDisabledOperationCompleted(object arg) {
            if ((this.getDisabledCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDisabledCompleted(this, new getDisabledCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="gs.az.tr", ResponseNamespace="gs.az.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getVisible([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] field arg2, [System.Xml.Serialization.XmlElementAttribute("arg3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] field[] arg3, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out bool @return, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] out bool returnSpecified) {
            object[] results = this.Invoke("getVisible", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3});
            @return = ((bool)(results[0]));
            returnSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void getVisibleAsync(string arg0, string arg1, field arg2, field[] arg3) {
            this.getVisibleAsync(arg0, arg1, arg2, arg3, null);
        }
        
        /// <remarks/>
        public void getVisibleAsync(string arg0, string arg1, field arg2, field[] arg3, object userState) {
            if ((this.getVisibleOperationCompleted == null)) {
                this.getVisibleOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVisibleOperationCompleted);
            }
            this.InvokeAsync("getVisible", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3}, this.getVisibleOperationCompleted, userState);
        }
        
        private void OngetVisibleOperationCompleted(object arg) {
            if ((this.getVisibleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVisibleCompleted(this, new getVisibleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gs.az.tr")]
    public partial class serviceCommand {
        
        private string clientIPField;
        
        private command commandField;
        
        private conversationKey keyField;
        
        private objectData objectDataField;
        
        private string processCodeField;
        
        private string processStepNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientIP {
            get {
                return this.clientIPField;
            }
            set {
                this.clientIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public command command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public conversationKey key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public objectData objectData {
            get {
                return this.objectDataField;
            }
            set {
                this.objectDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string processCode {
            get {
                return this.processCodeField;
            }
            set {
                this.processCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string processStepName {
            get {
                return this.processStepNameField;
            }
            set {
                this.processStepNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gs.az.tr")]
    public partial class command {
        
        private string commandNameField;
        
        private string commandTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string commandName {
            get {
                return this.commandNameField;
            }
            set {
                this.commandNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string commandText {
            get {
                return this.commandTextField;
            }
            set {
                this.commandTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gs.az.tr")]
    public partial class value {
        
        private string keyField;
        
        private bool predefinedField;
        
        private bool predefinedFieldSpecified;
        
        private string value1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool predefined {
            get {
                return this.predefinedField;
            }
            set {
                this.predefinedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool predefinedSpecified {
            get {
                return this.predefinedFieldSpecified;
            }
            set {
                this.predefinedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value1 {
            get {
                return this.value1Field;
            }
            set {
                this.value1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gs.az.tr")]
    public partial class valueSet {
        
        private bool cacheableField;
        
        private value[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool cacheable {
            get {
                return this.cacheableField;
            }
            set {
                this.cacheableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("values", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public value[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gs.az.tr")]
    public partial class fieldDescriptor {
        
        private string defaultValueField;
        
        private fieldDescriptor[] disableDependencyField;
        
        private string displayHintField;
        
        private string fieldNameField;
        
        private string fieldTypeField;
        
        private string labelField;
        
        private bool secondPhaseField;
        
        private fieldDescriptor[] valueDependencyField;
        
        private bool valueSetField;
        
        private fieldDescriptor[] visibleDependencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string defaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("disableDependency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public fieldDescriptor[] disableDependency {
            get {
                return this.disableDependencyField;
            }
            set {
                this.disableDependencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string displayHint {
            get {
                return this.displayHintField;
            }
            set {
                this.displayHintField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fieldType {
            get {
                return this.fieldTypeField;
            }
            set {
                this.fieldTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool secondPhase {
            get {
                return this.secondPhaseField;
            }
            set {
                this.secondPhaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("valueDependency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public fieldDescriptor[] valueDependency {
            get {
                return this.valueDependencyField;
            }
            set {
                this.valueDependencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool valueSet {
            get {
                return this.valueSetField;
            }
            set {
                this.valueSetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("visibleDependency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public fieldDescriptor[] visibleDependency {
            get {
                return this.visibleDependencyField;
            }
            set {
                this.visibleDependencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gs.az.tr")]
    public partial class objectDescriptor {
        
        private string entityClassField;
        
        private fieldDescriptor[] fieldDescriptorsField;
        
        private string objectNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string entityClass {
            get {
                return this.entityClassField;
            }
            set {
                this.entityClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fieldDescriptors", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public fieldDescriptor[] fieldDescriptors {
            get {
                return this.fieldDescriptorsField;
            }
            set {
                this.fieldDescriptorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string objectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gs.az.tr")]
    public partial class processStep {
        
        private bool asyncField;
        
        private command[] commandsField;
        
        private objectDescriptor requestObjectDescriptorField;
        
        private objectDescriptor responseObjectDescriptorField;
        
        private string stepNameField;
        
        private int syncTimeoutField;
        
        private bool syncTimeoutFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool async {
            get {
                return this.asyncField;
            }
            set {
                this.asyncField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("commands", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public command[] commands {
            get {
                return this.commandsField;
            }
            set {
                this.commandsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public objectDescriptor requestObjectDescriptor {
            get {
                return this.requestObjectDescriptorField;
            }
            set {
                this.requestObjectDescriptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public objectDescriptor responseObjectDescriptor {
            get {
                return this.responseObjectDescriptorField;
            }
            set {
                this.responseObjectDescriptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stepName {
            get {
                return this.stepNameField;
            }
            set {
                this.stepNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int syncTimeout {
            get {
                return this.syncTimeoutField;
            }
            set {
                this.syncTimeoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool syncTimeoutSpecified {
            get {
                return this.syncTimeoutFieldSpecified;
            }
            set {
                this.syncTimeoutFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gs.az.tr")]
    public partial class processDescriptor {
        
        private bool isRestFulField;
        
        private string processCodeField;
        
        private string processDescriptionField;
        
        private string processNameField;
        
        private processStep[] processStepsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isRestFul {
            get {
                return this.isRestFulField;
            }
            set {
                this.isRestFulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string processCode {
            get {
                return this.processCodeField;
            }
            set {
                this.processCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string processDescription {
            get {
                return this.processDescriptionField;
            }
            set {
                this.processDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string processName {
            get {
                return this.processNameField;
            }
            set {
                this.processNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("processSteps", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public processStep[] processSteps {
            get {
                return this.processStepsField;
            }
            set {
                this.processStepsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gs.az.tr")]
    public partial class serviceMessage {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gs.az.tr")]
    public partial class serviceCommandResult {
        
        private command[] availableCommandsField;
        
        private conversationKey keyField;
        
        private string processCodeField;
        
        private string processStepNameField;
        
        private objectData responseObjectField;
        
        private serviceMessage[] serviceMessagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("availableCommands", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public command[] availableCommands {
            get {
                return this.availableCommandsField;
            }
            set {
                this.availableCommandsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public conversationKey key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string processCode {
            get {
                return this.processCodeField;
            }
            set {
                this.processCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string processStepName {
            get {
                return this.processStepNameField;
            }
            set {
                this.processStepNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public objectData responseObject {
            get {
                return this.responseObjectField;
            }
            set {
                this.responseObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceMessages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public serviceMessage[] serviceMessages {
            get {
                return this.serviceMessagesField;
            }
            set {
                this.serviceMessagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gs.az.tr")]
    public partial class conversationKey {
        
        private string clientKeyField;
        
        private string serverKeyField;
        
        private string subjectIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientKey {
            get {
                return this.clientKeyField;
            }
            set {
                this.clientKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serverKey {
            get {
                return this.serverKeyField;
            }
            set {
                this.serverKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subjectId {
            get {
                return this.subjectIdField;
            }
            set {
                this.subjectIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gs.az.tr")]
    public partial class objectData {
        
        private fieldState[] fieldStatesField;
        
        private field[] fieldsField;
        
        private string objcetNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fieldStates", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public fieldState[] fieldStates {
            get {
                return this.fieldStatesField;
            }
            set {
                this.fieldStatesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fields", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public field[] fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string objcetName {
            get {
                return this.objcetNameField;
            }
            set {
                this.objcetNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gs.az.tr")]
    public partial class fieldState {
        
        private bool disabledField;
        
        private string fieldNameField;
        
        private bool visibleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool disabled {
            get {
                return this.disabledField;
            }
            set {
                this.disabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="gs.az.tr")]
    public partial class field {
        
        private string fieldNameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void executeCompletedEventHandler(object sender, executeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class executeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal executeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public serviceCommandResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((serviceCommandResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void listProcessDescriptorsCompletedEventHandler(object sender, listProcessDescriptorsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listProcessDescriptorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listProcessDescriptorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public processDescriptor[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((processDescriptor[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getProcessDescriptorCompletedEventHandler(object sender, getProcessDescriptorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getProcessDescriptorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getProcessDescriptorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public processDescriptor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((processDescriptor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getObjectDescriptorCompletedEventHandler(object sender, getObjectDescriptorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getObjectDescriptorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getObjectDescriptorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public objectDescriptor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((objectDescriptor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void setConlog_idCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getConlog_idCompletedEventHandler(object sender, getConlog_idCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getConlog_idCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getConlog_idCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getValueSetCompletedEventHandler(object sender, getValueSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getValueSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getValueSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public valueSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((valueSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getDisabledCompletedEventHandler(object sender, getDisabledCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDisabledCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDisabledCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool @return {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool returnSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getVisibleCompletedEventHandler(object sender, getVisibleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVisibleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVisibleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool @return {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool returnSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591