//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Neosinerji.BABOnlineTP.Business.aksigorta.basim {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PolicePDFSorgulamaWebServiceImplPortBinding", Namespace="http://policePDFSorgulama.police.webServices.aksigorta.tr.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseWSType))]
    public partial class policeBasimBilgileriPolicePDFSorgulamaWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback policePDFSorgulamaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public policeBasimBilgileriPolicePDFSorgulamaWebService() {
            this.Url = global::Neosinerji.BABOnlineTP.Business.Properties.Settings.Default.Neosinerji_BABOnlineTP_Business_aksigorta_basim__policeBasimBilgileri_PolicePDFSorgulamaWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event policePDFSorgulamaCompletedEventHandler policePDFSorgulamaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://policePDFSorgulama.police.webServices.aksigorta.tr.com/", ResponseNamespace="http://policePDFSorgulama.police.webServices.aksigorta.tr.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] policePDFSorgulama([System.Xml.Serialization.XmlElementAttribute("policePDFSorgulama", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] policePDFSorguInput policePDFSorgulama1) {
            object[] results = this.Invoke("policePDFSorgulama", new object[] {
                        policePDFSorgulama1});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void policePDFSorgulamaAsync(policePDFSorguInput policePDFSorgulama1) {
            this.policePDFSorgulamaAsync(policePDFSorgulama1, null);
        }
        
        /// <remarks/>
        public void policePDFSorgulamaAsync(policePDFSorguInput policePDFSorgulama1, object userState) {
            if ((this.policePDFSorgulamaOperationCompleted == null)) {
                this.policePDFSorgulamaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpolicePDFSorgulamaOperationCompleted);
            }
            this.InvokeAsync("policePDFSorgulama", new object[] {
                        policePDFSorgulama1}, this.policePDFSorgulamaOperationCompleted, userState);
        }
        
        private void OnpolicePDFSorgulamaOperationCompleted(object arg) {
            if ((this.policePDFSorgulamaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.policePDFSorgulamaCompleted(this, new policePDFSorgulamaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://policePDFSorgulama.police.webServices.aksigorta.tr.com/")]
    public partial class policePDFSorguInput {
        
        private kanalBilgileriType kanalBilgileriField;
        
        private string policeNoField;
        
        private string basimDiliField;
        
        private string zeylSiraNoField;
        
        private basimTipi basimTipiField;
        
        private bool basimTipiFieldSpecified;
        
        private string satisIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public kanalBilgileriType kanalBilgileri {
            get {
                return this.kanalBilgileriField;
            }
            set {
                this.kanalBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string policeNo {
            get {
                return this.policeNoField;
            }
            set {
                this.policeNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string basimDili {
            get {
                return this.basimDiliField;
            }
            set {
                this.basimDiliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string zeylSiraNo {
            get {
                return this.zeylSiraNoField;
            }
            set {
                this.zeylSiraNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public basimTipi basimTipi {
            get {
                return this.basimTipiField;
            }
            set {
                this.basimTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool basimTipiSpecified {
            get {
                return this.basimTipiFieldSpecified;
            }
            set {
                this.basimTipiFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string satisId {
            get {
                return this.satisIdField;
            }
            set {
                this.satisIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://policePDFSorgulama.police.webServices.aksigorta.tr.com/")]
    public partial class kanalBilgileriType : baseWSType {
        
        private string kanalIdField;
        
        private string branchIdField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string kanalId {
            get {
                return this.kanalIdField;
            }
            set {
                this.kanalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string branchId {
            get {
                return this.branchIdField;
            }
            set {
                this.branchIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(kanalBilgileriType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://policePDFSorgulama.police.webServices.aksigorta.tr.com/")]
    public abstract partial class baseWSType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://policePDFSorgulama.police.webServices.aksigorta.tr.com/")]
    public enum basimTipi {
        
        /// <remarks/>
        POLICE_BASIM,
        
        /// <remarks/>
        BILGILENDIRME_FORMU,
        
        /// <remarks/>
        TAHSILAT_MAKBUZU,
        
        /// <remarks/>
        TUM_DOKUMANLAR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void policePDFSorgulamaCompletedEventHandler(object sender, policePDFSorgulamaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class policePDFSorgulamaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal policePDFSorgulamaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591