//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DataSharetest.DataShare {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AO_DataShare_Service01Soap", Namespace="http://aodatashare.axaoyak.com.tr/webservices/")]
    public partial class AO_DataShare_Service01 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetPolicyDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPolicyDetailsLastOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPoliciesListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTarifeOperationCompleted;
        
        private System.Threading.SendOrPostCallback TransferYapildiOperationCompleted;
        
        private System.Threading.SendOrPostCallback TransferIptalOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTransferListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOdemePlaniDegismisPolicelerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAltPoliceListesiOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIstDegerlerOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindPlakaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBransListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDovizListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVergiListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTarifeListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTarifeZeylListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AO_DataShare_Service01() {
           // this.Url = global::DataSharetest.Properties.Settings.Default.DataSharetest_DataShare_AO_DataShare_Service01;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetPolicyDetailsCompletedEventHandler GetPolicyDetailsCompleted;
        
        /// <remarks/>
        public event GetPolicyDetailsLastCompletedEventHandler GetPolicyDetailsLastCompleted;
        
        /// <remarks/>
        public event GetPoliciesListCompletedEventHandler GetPoliciesListCompleted;
        
        /// <remarks/>
        public event GetTarifeCompletedEventHandler GetTarifeCompleted;
        
        /// <remarks/>
        public event TransferYapildiCompletedEventHandler TransferYapildiCompleted;
        
        /// <remarks/>
        public event TransferIptalCompletedEventHandler TransferIptalCompleted;
        
        /// <remarks/>
        public event GetTransferListCompletedEventHandler GetTransferListCompleted;
        
        /// <remarks/>
        public event GetOdemePlaniDegismisPolicelerCompletedEventHandler GetOdemePlaniDegismisPolicelerCompleted;
        
        /// <remarks/>
        public event GetAltPoliceListesiCompletedEventHandler GetAltPoliceListesiCompleted;
        
        /// <remarks/>
        public event GetIstDegerlerCompletedEventHandler GetIstDegerlerCompleted;
        
        /// <remarks/>
        public event FindPlakaCompletedEventHandler FindPlakaCompleted;
        
        /// <remarks/>
        public event GetBransListCompletedEventHandler GetBransListCompleted;
        
        /// <remarks/>
        public event GetDovizListCompletedEventHandler GetDovizListCompleted;
        
        /// <remarks/>
        public event GetVergiListCompletedEventHandler GetVergiListCompleted;
        
        /// <remarks/>
        public event GetTarifeListCompletedEventHandler GetTarifeListCompleted;
        
        /// <remarks/>
        public event GetTarifeZeylListCompletedEventHandler GetTarifeZeylListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aodatashare.axaoyak.com.tr/webservices/GetPolicyDetails", RequestNamespace="http://aodatashare.axaoyak.com.tr/webservices/", ResponseNamespace="http://aodatashare.axaoyak.com.tr/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetPolicyDetails(int pSirket_Kod, int pCari_Pol_No, int pZeyl_Sira_No) {
            object[] results = this.Invoke("GetPolicyDetails", new object[] {
                        pSirket_Kod,
                        pCari_Pol_No,
                        pZeyl_Sira_No});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetPolicyDetailsAsync(int pSirket_Kod, int pCari_Pol_No, int pZeyl_Sira_No) {
            this.GetPolicyDetailsAsync(pSirket_Kod, pCari_Pol_No, pZeyl_Sira_No, null);
        }
        
        /// <remarks/>
        public void GetPolicyDetailsAsync(int pSirket_Kod, int pCari_Pol_No, int pZeyl_Sira_No, object userState) {
            if ((this.GetPolicyDetailsOperationCompleted == null)) {
                this.GetPolicyDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPolicyDetailsOperationCompleted);
            }
            this.InvokeAsync("GetPolicyDetails", new object[] {
                        pSirket_Kod,
                        pCari_Pol_No,
                        pZeyl_Sira_No}, this.GetPolicyDetailsOperationCompleted, userState);
        }
        
        private void OnGetPolicyDetailsOperationCompleted(object arg) {
            if ((this.GetPolicyDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPolicyDetailsCompleted(this, new GetPolicyDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aodatashare.axaoyak.com.tr/webservices/GetPolicyDetailsLast", RequestNamespace="http://aodatashare.axaoyak.com.tr/webservices/", ResponseNamespace="http://aodatashare.axaoyak.com.tr/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetPolicyDetailsLast(int pSirket_Kod, int pCari_Pol_No, string pTarih) {
            object[] results = this.Invoke("GetPolicyDetailsLast", new object[] {
                        pSirket_Kod,
                        pCari_Pol_No,
                        pTarih});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetPolicyDetailsLastAsync(int pSirket_Kod, int pCari_Pol_No, string pTarih) {
            this.GetPolicyDetailsLastAsync(pSirket_Kod, pCari_Pol_No, pTarih, null);
        }
        
        /// <remarks/>
        public void GetPolicyDetailsLastAsync(int pSirket_Kod, int pCari_Pol_No, string pTarih, object userState) {
            if ((this.GetPolicyDetailsLastOperationCompleted == null)) {
                this.GetPolicyDetailsLastOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPolicyDetailsLastOperationCompleted);
            }
            this.InvokeAsync("GetPolicyDetailsLast", new object[] {
                        pSirket_Kod,
                        pCari_Pol_No,
                        pTarih}, this.GetPolicyDetailsLastOperationCompleted, userState);
        }
        
        private void OnGetPolicyDetailsLastOperationCompleted(object arg) {
            if ((this.GetPolicyDetailsLastCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPolicyDetailsLastCompleted(this, new GetPolicyDetailsLastCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aodatashare.axaoyak.com.tr/webservices/GetPoliciesList", RequestNamespace="http://aodatashare.axaoyak.com.tr/webservices/", ResponseNamespace="http://aodatashare.axaoyak.com.tr/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetPoliciesList(int pSirket_Kod, string pTanzimTarih1, string pTanzimTarih2, int pTeklif_Onay) {
            object[] results = this.Invoke("GetPoliciesList", new object[] {
                        pSirket_Kod,
                        pTanzimTarih1,
                        pTanzimTarih2,
                        pTeklif_Onay});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetPoliciesListAsync(int pSirket_Kod, string pTanzimTarih1, string pTanzimTarih2, int pTeklif_Onay) {
            this.GetPoliciesListAsync(pSirket_Kod, pTanzimTarih1, pTanzimTarih2, pTeklif_Onay, null);
        }
        
        /// <remarks/>
        public void GetPoliciesListAsync(int pSirket_Kod, string pTanzimTarih1, string pTanzimTarih2, int pTeklif_Onay, object userState) {
            if ((this.GetPoliciesListOperationCompleted == null)) {
                this.GetPoliciesListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPoliciesListOperationCompleted);
            }
            this.InvokeAsync("GetPoliciesList", new object[] {
                        pSirket_Kod,
                        pTanzimTarih1,
                        pTanzimTarih2,
                        pTeklif_Onay}, this.GetPoliciesListOperationCompleted, userState);
        }
        
        private void OnGetPoliciesListOperationCompleted(object arg) {
            if ((this.GetPoliciesListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPoliciesListCompleted(this, new GetPoliciesListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aodatashare.axaoyak.com.tr/webservices/GetTarife", RequestNamespace="http://aodatashare.axaoyak.com.tr/webservices/", ResponseNamespace="http://aodatashare.axaoyak.com.tr/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetTarife(int pSirket_Kod, string pTarife_Kod, int pVK) {
            object[] results = this.Invoke("GetTarife", new object[] {
                        pSirket_Kod,
                        pTarife_Kod,
                        pVK});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetTarifeAsync(int pSirket_Kod, string pTarife_Kod, int pVK) {
            this.GetTarifeAsync(pSirket_Kod, pTarife_Kod, pVK, null);
        }
        
        /// <remarks/>
        public void GetTarifeAsync(int pSirket_Kod, string pTarife_Kod, int pVK, object userState) {
            if ((this.GetTarifeOperationCompleted == null)) {
                this.GetTarifeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTarifeOperationCompleted);
            }
            this.InvokeAsync("GetTarife", new object[] {
                        pSirket_Kod,
                        pTarife_Kod,
                        pVK}, this.GetTarifeOperationCompleted, userState);
        }
        
        private void OnGetTarifeOperationCompleted(object arg) {
            if ((this.GetTarifeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTarifeCompleted(this, new GetTarifeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aodatashare.axaoyak.com.tr/webservices/TransferYapildi", RequestNamespace="http://aodatashare.axaoyak.com.tr/webservices/", ResponseNamespace="http://aodatashare.axaoyak.com.tr/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode TransferYapildi(int pSirket_Kod, int pCari_Pol_No, int pZeyl_Sira_No) {
            object[] results = this.Invoke("TransferYapildi", new object[] {
                        pSirket_Kod,
                        pCari_Pol_No,
                        pZeyl_Sira_No});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void TransferYapildiAsync(int pSirket_Kod, int pCari_Pol_No, int pZeyl_Sira_No) {
            this.TransferYapildiAsync(pSirket_Kod, pCari_Pol_No, pZeyl_Sira_No, null);
        }
        
        /// <remarks/>
        public void TransferYapildiAsync(int pSirket_Kod, int pCari_Pol_No, int pZeyl_Sira_No, object userState) {
            if ((this.TransferYapildiOperationCompleted == null)) {
                this.TransferYapildiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTransferYapildiOperationCompleted);
            }
            this.InvokeAsync("TransferYapildi", new object[] {
                        pSirket_Kod,
                        pCari_Pol_No,
                        pZeyl_Sira_No}, this.TransferYapildiOperationCompleted, userState);
        }
        
        private void OnTransferYapildiOperationCompleted(object arg) {
            if ((this.TransferYapildiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TransferYapildiCompleted(this, new TransferYapildiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aodatashare.axaoyak.com.tr/webservices/TransferIptal", RequestNamespace="http://aodatashare.axaoyak.com.tr/webservices/", ResponseNamespace="http://aodatashare.axaoyak.com.tr/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode TransferIptal(int pSirket_Kod, int pCari_Pol_No, int pZeyl_Sira_No) {
            object[] results = this.Invoke("TransferIptal", new object[] {
                        pSirket_Kod,
                        pCari_Pol_No,
                        pZeyl_Sira_No});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void TransferIptalAsync(int pSirket_Kod, int pCari_Pol_No, int pZeyl_Sira_No) {
            this.TransferIptalAsync(pSirket_Kod, pCari_Pol_No, pZeyl_Sira_No, null);
        }
        
        /// <remarks/>
        public void TransferIptalAsync(int pSirket_Kod, int pCari_Pol_No, int pZeyl_Sira_No, object userState) {
            if ((this.TransferIptalOperationCompleted == null)) {
                this.TransferIptalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTransferIptalOperationCompleted);
            }
            this.InvokeAsync("TransferIptal", new object[] {
                        pSirket_Kod,
                        pCari_Pol_No,
                        pZeyl_Sira_No}, this.TransferIptalOperationCompleted, userState);
        }
        
        private void OnTransferIptalOperationCompleted(object arg) {
            if ((this.TransferIptalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TransferIptalCompleted(this, new TransferIptalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aodatashare.axaoyak.com.tr/webservices/GetTransferList", RequestNamespace="http://aodatashare.axaoyak.com.tr/webservices/", ResponseNamespace="http://aodatashare.axaoyak.com.tr/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetTransferList(int pSirket_Kod, string pTanzimTarih1, string pTanzimTarih2, int pDurum) {
            object[] results = this.Invoke("GetTransferList", new object[] {
                        pSirket_Kod,
                        pTanzimTarih1,
                        pTanzimTarih2,
                        pDurum});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransferListAsync(int pSirket_Kod, string pTanzimTarih1, string pTanzimTarih2, int pDurum) {
            this.GetTransferListAsync(pSirket_Kod, pTanzimTarih1, pTanzimTarih2, pDurum, null);
        }
        
        /// <remarks/>
        public void GetTransferListAsync(int pSirket_Kod, string pTanzimTarih1, string pTanzimTarih2, int pDurum, object userState) {
            if ((this.GetTransferListOperationCompleted == null)) {
                this.GetTransferListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransferListOperationCompleted);
            }
            this.InvokeAsync("GetTransferList", new object[] {
                        pSirket_Kod,
                        pTanzimTarih1,
                        pTanzimTarih2,
                        pDurum}, this.GetTransferListOperationCompleted, userState);
        }
        
        private void OnGetTransferListOperationCompleted(object arg) {
            if ((this.GetTransferListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransferListCompleted(this, new GetTransferListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aodatashare.axaoyak.com.tr/webservices/GetOdemePlaniDegismisPoliceler", RequestNamespace="http://aodatashare.axaoyak.com.tr/webservices/", ResponseNamespace="http://aodatashare.axaoyak.com.tr/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetOdemePlaniDegismisPoliceler(int pSirket_Kod, string pTanzimTarih1, string pTanzimTarih2) {
            object[] results = this.Invoke("GetOdemePlaniDegismisPoliceler", new object[] {
                        pSirket_Kod,
                        pTanzimTarih1,
                        pTanzimTarih2});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetOdemePlaniDegismisPolicelerAsync(int pSirket_Kod, string pTanzimTarih1, string pTanzimTarih2) {
            this.GetOdemePlaniDegismisPolicelerAsync(pSirket_Kod, pTanzimTarih1, pTanzimTarih2, null);
        }
        
        /// <remarks/>
        public void GetOdemePlaniDegismisPolicelerAsync(int pSirket_Kod, string pTanzimTarih1, string pTanzimTarih2, object userState) {
            if ((this.GetOdemePlaniDegismisPolicelerOperationCompleted == null)) {
                this.GetOdemePlaniDegismisPolicelerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOdemePlaniDegismisPolicelerOperationCompleted);
            }
            this.InvokeAsync("GetOdemePlaniDegismisPoliceler", new object[] {
                        pSirket_Kod,
                        pTanzimTarih1,
                        pTanzimTarih2}, this.GetOdemePlaniDegismisPolicelerOperationCompleted, userState);
        }
        
        private void OnGetOdemePlaniDegismisPolicelerOperationCompleted(object arg) {
            if ((this.GetOdemePlaniDegismisPolicelerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOdemePlaniDegismisPolicelerCompleted(this, new GetOdemePlaniDegismisPolicelerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aodatashare.axaoyak.com.tr/webservices/GetAltPoliceListesi", RequestNamespace="http://aodatashare.axaoyak.com.tr/webservices/", ResponseNamespace="http://aodatashare.axaoyak.com.tr/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetAltPoliceListesi(int pSirket_Kod, int pBagli_Pol_No, string pPolice_Ekbelge, string pTanzimTarih1, string pTanzimTarih2, int pTeklif_Onay) {
            object[] results = this.Invoke("GetAltPoliceListesi", new object[] {
                        pSirket_Kod,
                        pBagli_Pol_No,
                        pPolice_Ekbelge,
                        pTanzimTarih1,
                        pTanzimTarih2,
                        pTeklif_Onay});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetAltPoliceListesiAsync(int pSirket_Kod, int pBagli_Pol_No, string pPolice_Ekbelge, string pTanzimTarih1, string pTanzimTarih2, int pTeklif_Onay) {
            this.GetAltPoliceListesiAsync(pSirket_Kod, pBagli_Pol_No, pPolice_Ekbelge, pTanzimTarih1, pTanzimTarih2, pTeklif_Onay, null);
        }
        
        /// <remarks/>
        public void GetAltPoliceListesiAsync(int pSirket_Kod, int pBagli_Pol_No, string pPolice_Ekbelge, string pTanzimTarih1, string pTanzimTarih2, int pTeklif_Onay, object userState) {
            if ((this.GetAltPoliceListesiOperationCompleted == null)) {
                this.GetAltPoliceListesiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAltPoliceListesiOperationCompleted);
            }
            this.InvokeAsync("GetAltPoliceListesi", new object[] {
                        pSirket_Kod,
                        pBagli_Pol_No,
                        pPolice_Ekbelge,
                        pTanzimTarih1,
                        pTanzimTarih2,
                        pTeklif_Onay}, this.GetAltPoliceListesiOperationCompleted, userState);
        }
        
        private void OnGetAltPoliceListesiOperationCompleted(object arg) {
            if ((this.GetAltPoliceListesiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAltPoliceListesiCompleted(this, new GetAltPoliceListesiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aodatashare.axaoyak.com.tr/webservices/GetIstDegerler", RequestNamespace="http://aodatashare.axaoyak.com.tr/webservices/", ResponseNamespace="http://aodatashare.axaoyak.com.tr/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetIstDegerler(int pSirket_Kod, string pIst_Kod) {
            object[] results = this.Invoke("GetIstDegerler", new object[] {
                        pSirket_Kod,
                        pIst_Kod});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetIstDegerlerAsync(int pSirket_Kod, string pIst_Kod) {
            this.GetIstDegerlerAsync(pSirket_Kod, pIst_Kod, null);
        }
        
        /// <remarks/>
        public void GetIstDegerlerAsync(int pSirket_Kod, string pIst_Kod, object userState) {
            if ((this.GetIstDegerlerOperationCompleted == null)) {
                this.GetIstDegerlerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIstDegerlerOperationCompleted);
            }
            this.InvokeAsync("GetIstDegerler", new object[] {
                        pSirket_Kod,
                        pIst_Kod}, this.GetIstDegerlerOperationCompleted, userState);
        }
        
        private void OnGetIstDegerlerOperationCompleted(object arg) {
            if ((this.GetIstDegerlerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIstDegerlerCompleted(this, new GetIstDegerlerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aodatashare.axaoyak.com.tr/webservices/FindPlaka", RequestNamespace="http://aodatashare.axaoyak.com.tr/webservices/", ResponseNamespace="http://aodatashare.axaoyak.com.tr/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode FindPlaka(int pSirket_Kod, string pPlaka_No, string pBrans_Kod, int pTeklif_Onay) {
            object[] results = this.Invoke("FindPlaka", new object[] {
                        pSirket_Kod,
                        pPlaka_No,
                        pBrans_Kod,
                        pTeklif_Onay});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void FindPlakaAsync(int pSirket_Kod, string pPlaka_No, string pBrans_Kod, int pTeklif_Onay) {
            this.FindPlakaAsync(pSirket_Kod, pPlaka_No, pBrans_Kod, pTeklif_Onay, null);
        }
        
        /// <remarks/>
        public void FindPlakaAsync(int pSirket_Kod, string pPlaka_No, string pBrans_Kod, int pTeklif_Onay, object userState) {
            if ((this.FindPlakaOperationCompleted == null)) {
                this.FindPlakaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindPlakaOperationCompleted);
            }
            this.InvokeAsync("FindPlaka", new object[] {
                        pSirket_Kod,
                        pPlaka_No,
                        pBrans_Kod,
                        pTeklif_Onay}, this.FindPlakaOperationCompleted, userState);
        }
        
        private void OnFindPlakaOperationCompleted(object arg) {
            if ((this.FindPlakaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindPlakaCompleted(this, new FindPlakaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aodatashare.axaoyak.com.tr/webservices/GetBransList", RequestNamespace="http://aodatashare.axaoyak.com.tr/webservices/", ResponseNamespace="http://aodatashare.axaoyak.com.tr/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetBransList(int pSirket_Kod) {
            object[] results = this.Invoke("GetBransList", new object[] {
                        pSirket_Kod});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetBransListAsync(int pSirket_Kod) {
            this.GetBransListAsync(pSirket_Kod, null);
        }
        
        /// <remarks/>
        public void GetBransListAsync(int pSirket_Kod, object userState) {
            if ((this.GetBransListOperationCompleted == null)) {
                this.GetBransListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBransListOperationCompleted);
            }
            this.InvokeAsync("GetBransList", new object[] {
                        pSirket_Kod}, this.GetBransListOperationCompleted, userState);
        }
        
        private void OnGetBransListOperationCompleted(object arg) {
            if ((this.GetBransListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBransListCompleted(this, new GetBransListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aodatashare.axaoyak.com.tr/webservices/GetDovizList", RequestNamespace="http://aodatashare.axaoyak.com.tr/webservices/", ResponseNamespace="http://aodatashare.axaoyak.com.tr/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetDovizList(int pSirket_Kod) {
            object[] results = this.Invoke("GetDovizList", new object[] {
                        pSirket_Kod});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetDovizListAsync(int pSirket_Kod) {
            this.GetDovizListAsync(pSirket_Kod, null);
        }
        
        /// <remarks/>
        public void GetDovizListAsync(int pSirket_Kod, object userState) {
            if ((this.GetDovizListOperationCompleted == null)) {
                this.GetDovizListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDovizListOperationCompleted);
            }
            this.InvokeAsync("GetDovizList", new object[] {
                        pSirket_Kod}, this.GetDovizListOperationCompleted, userState);
        }
        
        private void OnGetDovizListOperationCompleted(object arg) {
            if ((this.GetDovizListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDovizListCompleted(this, new GetDovizListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aodatashare.axaoyak.com.tr/webservices/GetVergiList", RequestNamespace="http://aodatashare.axaoyak.com.tr/webservices/", ResponseNamespace="http://aodatashare.axaoyak.com.tr/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetVergiList(int pSirket_Kod) {
            object[] results = this.Invoke("GetVergiList", new object[] {
                        pSirket_Kod});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetVergiListAsync(int pSirket_Kod) {
            this.GetVergiListAsync(pSirket_Kod, null);
        }
        
        /// <remarks/>
        public void GetVergiListAsync(int pSirket_Kod, object userState) {
            if ((this.GetVergiListOperationCompleted == null)) {
                this.GetVergiListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVergiListOperationCompleted);
            }
            this.InvokeAsync("GetVergiList", new object[] {
                        pSirket_Kod}, this.GetVergiListOperationCompleted, userState);
        }
        
        private void OnGetVergiListOperationCompleted(object arg) {
            if ((this.GetVergiListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVergiListCompleted(this, new GetVergiListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aodatashare.axaoyak.com.tr/webservices/GetTarifeList", RequestNamespace="http://aodatashare.axaoyak.com.tr/webservices/", ResponseNamespace="http://aodatashare.axaoyak.com.tr/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetTarifeList(int pSirket_Kod) {
            object[] results = this.Invoke("GetTarifeList", new object[] {
                        pSirket_Kod});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetTarifeListAsync(int pSirket_Kod) {
            this.GetTarifeListAsync(pSirket_Kod, null);
        }
        
        /// <remarks/>
        public void GetTarifeListAsync(int pSirket_Kod, object userState) {
            if ((this.GetTarifeListOperationCompleted == null)) {
                this.GetTarifeListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTarifeListOperationCompleted);
            }
            this.InvokeAsync("GetTarifeList", new object[] {
                        pSirket_Kod}, this.GetTarifeListOperationCompleted, userState);
        }
        
        private void OnGetTarifeListOperationCompleted(object arg) {
            if ((this.GetTarifeListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTarifeListCompleted(this, new GetTarifeListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://aodatashare.axaoyak.com.tr/webservices/GetTarifeZeylList", RequestNamespace="http://aodatashare.axaoyak.com.tr/webservices/", ResponseNamespace="http://aodatashare.axaoyak.com.tr/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetTarifeZeylList(int pSirket_Kod, string pTarife_Kod) {
            object[] results = this.Invoke("GetTarifeZeylList", new object[] {
                        pSirket_Kod,
                        pTarife_Kod});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetTarifeZeylListAsync(int pSirket_Kod, string pTarife_Kod) {
            this.GetTarifeZeylListAsync(pSirket_Kod, pTarife_Kod, null);
        }
        
        /// <remarks/>
        public void GetTarifeZeylListAsync(int pSirket_Kod, string pTarife_Kod, object userState) {
            if ((this.GetTarifeZeylListOperationCompleted == null)) {
                this.GetTarifeZeylListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTarifeZeylListOperationCompleted);
            }
            this.InvokeAsync("GetTarifeZeylList", new object[] {
                        pSirket_Kod,
                        pTarife_Kod}, this.GetTarifeZeylListOperationCompleted, userState);
        }
        
        private void OnGetTarifeZeylListOperationCompleted(object arg) {
            if ((this.GetTarifeZeylListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTarifeZeylListCompleted(this, new GetTarifeZeylListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetPolicyDetailsCompletedEventHandler(object sender, GetPolicyDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPolicyDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPolicyDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetPolicyDetailsLastCompletedEventHandler(object sender, GetPolicyDetailsLastCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPolicyDetailsLastCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPolicyDetailsLastCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetPoliciesListCompletedEventHandler(object sender, GetPoliciesListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPoliciesListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPoliciesListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetTarifeCompletedEventHandler(object sender, GetTarifeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTarifeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTarifeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void TransferYapildiCompletedEventHandler(object sender, TransferYapildiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransferYapildiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TransferYapildiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void TransferIptalCompletedEventHandler(object sender, TransferIptalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransferIptalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TransferIptalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetTransferListCompletedEventHandler(object sender, GetTransferListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransferListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransferListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetOdemePlaniDegismisPolicelerCompletedEventHandler(object sender, GetOdemePlaniDegismisPolicelerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOdemePlaniDegismisPolicelerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOdemePlaniDegismisPolicelerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetAltPoliceListesiCompletedEventHandler(object sender, GetAltPoliceListesiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAltPoliceListesiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAltPoliceListesiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetIstDegerlerCompletedEventHandler(object sender, GetIstDegerlerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIstDegerlerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIstDegerlerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void FindPlakaCompletedEventHandler(object sender, FindPlakaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindPlakaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindPlakaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetBransListCompletedEventHandler(object sender, GetBransListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBransListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBransListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetDovizListCompletedEventHandler(object sender, GetDovizListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDovizListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDovizListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetVergiListCompletedEventHandler(object sender, GetVergiListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVergiListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVergiListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetTarifeListCompletedEventHandler(object sender, GetTarifeListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTarifeListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTarifeListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetTarifeZeylListCompletedEventHandler(object sender, GetTarifeZeylListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTarifeZeylListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTarifeZeylListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591