//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18063.
// 
#pragma warning disable 1591

namespace Neosinerji.BABOnlineTP.Business.eureko.teminat {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PolicyComponentReadSoapBinding", Namespace="http://PolicyComponentRead.webservices.gb.com")]
    public partial class PolicyComponentReadService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ExecuteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PolicyComponentReadService() {
            this.Url = global::Neosinerji.BABOnlineTP.Business.Properties.Settings.Default.Neosinerji_BABOnlineTP_Business_eureko_teminat_PolicyComponentReadService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExecuteCompletedEventHandler ExecuteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://PolicyComponentRead.webservices.gb.com", ResponseNamespace="http://PolicyComponentRead.webservices.gb.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Response")]
        public ExecuteResponseResponse Execute(ExecuteRequest Request) {
            object[] results = this.Invoke("Execute", new object[] {
                        Request});
            return ((ExecuteResponseResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ExecuteAsync(ExecuteRequest Request) {
            this.ExecuteAsync(Request, null);
        }
        
        /// <remarks/>
        public void ExecuteAsync(ExecuteRequest Request, object userState) {
            if ((this.ExecuteOperationCompleted == null)) {
                this.ExecuteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteOperationCompleted);
            }
            this.InvokeAsync("Execute", new object[] {
                        Request}, this.ExecuteOperationCompleted, userState);
        }
        
        private void OnExecuteOperationCompleted(object arg) {
            if ((this.ExecuteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteCompleted(this, new ExecuteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://PolicyComponentRead.webservices.gb.com")]
    public partial class ExecuteRequest {
        
        private ExecuteRequestInHeader inHeaderField;
        
        private ExecuteRequestInPolicyMaster inPolicyMasterField;
        
        /// <remarks/>
        public ExecuteRequestInHeader InHeader {
            get {
                return this.inHeaderField;
            }
            set {
                this.inHeaderField = value;
            }
        }
        
        /// <remarks/>
        public ExecuteRequestInPolicyMaster InPolicyMaster {
            get {
                return this.inPolicyMasterField;
            }
            set {
                this.inPolicyMasterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://PolicyComponentRead.webservices.gb.com")]
    public partial class ExecuteRequestInHeader {
        
        private string companyIdField;
        
        private string userIdField;
        
        private string passwordField;
        
        private ExecuteRequestInHeaderPlatformType platformTypeField;
        
        private string messageIdField;
        
        /// <remarks/>
        public string CompanyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public ExecuteRequestInHeaderPlatformType PlatformType {
            get {
                return this.platformTypeField;
            }
            set {
                this.platformTypeField = value;
            }
        }
        
        /// <remarks/>
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://PolicyComponentRead.webservices.gb.com")]
    public enum ExecuteRequestInHeaderPlatformType {
        
        /// <remarks/>
        DVL,
        
        /// <remarks/>
        EGT,
        
        /// <remarks/>
        TST,
        
        /// <remarks/>
        PRD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://PolicyComponentRead.webservices.gb.com")]
    public partial class ExecuteRequestInPolicyMaster {
        
        private string companyCodeField;
        
        private string policyGroupNumField;
        
        private string policyNumField;
        
        private string renewalNumField;
        
        private string endorsementNumField;
        
        private string internalEndorsementNumField;
        
        private string changeSequenceNumField;
        
        /// <remarks/>
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string PolicyGroupNum {
            get {
                return this.policyGroupNumField;
            }
            set {
                this.policyGroupNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string PolicyNum {
            get {
                return this.policyNumField;
            }
            set {
                this.policyNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string RenewalNum {
            get {
                return this.renewalNumField;
            }
            set {
                this.renewalNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string EndorsementNum {
            get {
                return this.endorsementNumField;
            }
            set {
                this.endorsementNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string InternalEndorsementNum {
            get {
                return this.internalEndorsementNumField;
            }
            set {
                this.internalEndorsementNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ChangeSequenceNum {
            get {
                return this.changeSequenceNumField;
            }
            set {
                this.changeSequenceNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://PolicyComponentRead.webservices.gb.com")]
    public partial class ExecuteResponseResponse {
        
        private ExecuteResponseResponseOutHeader outHeaderField;
        
        private ExecuteResponseResponseOutGroupRow[] outGroupField;
        
        /// <remarks/>
        public ExecuteResponseResponseOutHeader OutHeader {
            get {
                return this.outHeaderField;
            }
            set {
                this.outHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OutGroupRow", IsNullable=false)]
        public ExecuteResponseResponseOutGroupRow[] OutGroup {
            get {
                return this.outGroupField;
            }
            set {
                this.outGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://PolicyComponentRead.webservices.gb.com")]
    public partial class ExecuteResponseResponseOutHeader {
        
        private string isSuccessfullField;
        
        private string responseMessageField;
        
        private string responseCodeField;
        
        /// <remarks/>
        public string IsSuccessfull {
            get {
                return this.isSuccessfullField;
            }
            set {
                this.isSuccessfullField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://PolicyComponentRead.webservices.gb.com")]
    public partial class ExecuteResponseResponseOutGroupRow {
        
        private ExecuteResponseResponseOutGroupRowOutGlobalInfo outGlobalInfoField;
        
        private ExecuteResponseResponseOutGroupRowOutPolicySumInsured outPolicySumInsuredField;
        
        private ExecuteResponseResponseOutGroupRowOutPolicyTax outPolicyTaxField;
        
        private ExecuteResponseResponseOutGroupRowOutIir1PolicyCommission outIir1PolicyCommissionField;
        
        private ExecuteResponseResponseOutGroupRowOutGrossPolicySumInsured outGrossPolicySumInsuredField;
        
        /// <remarks/>
        public ExecuteResponseResponseOutGroupRowOutGlobalInfo OutGlobalInfo {
            get {
                return this.outGlobalInfoField;
            }
            set {
                this.outGlobalInfoField = value;
            }
        }
        
        /// <remarks/>
        public ExecuteResponseResponseOutGroupRowOutPolicySumInsured OutPolicySumInsured {
            get {
                return this.outPolicySumInsuredField;
            }
            set {
                this.outPolicySumInsuredField = value;
            }
        }
        
        /// <remarks/>
        public ExecuteResponseResponseOutGroupRowOutPolicyTax OutPolicyTax {
            get {
                return this.outPolicyTaxField;
            }
            set {
                this.outPolicyTaxField = value;
            }
        }
        
        /// <remarks/>
        public ExecuteResponseResponseOutGroupRowOutIir1PolicyCommission OutIir1PolicyCommission {
            get {
                return this.outIir1PolicyCommissionField;
            }
            set {
                this.outIir1PolicyCommissionField = value;
            }
        }
        
        /// <remarks/>
        public ExecuteResponseResponseOutGroupRowOutGrossPolicySumInsured OutGrossPolicySumInsured {
            get {
                return this.outGrossPolicySumInsuredField;
            }
            set {
                this.outGrossPolicySumInsuredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://PolicyComponentRead.webservices.gb.com")]
    public partial class ExecuteResponseResponseOutGroupRowOutGlobalInfo {
        
        private string componentNameTextField;
        
        /// <remarks/>
        public string ComponentNameText {
            get {
                return this.componentNameTextField;
            }
            set {
                this.componentNameTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://PolicyComponentRead.webservices.gb.com")]
    public partial class ExecuteResponseResponseOutGroupRowOutPolicySumInsured {
        
        private string coverageMatrixNumField;
        
        private decimal sumInsuredAmountField;
        
        private decimal accruePremiumAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string CoverageMatrixNum {
            get {
                return this.coverageMatrixNumField;
            }
            set {
                this.coverageMatrixNumField = value;
            }
        }
        
        /// <remarks/>
        public decimal SumInsuredAmount {
            get {
                return this.sumInsuredAmountField;
            }
            set {
                this.sumInsuredAmountField = value;
            }
        }
        
        /// <remarks/>
        public decimal AccruePremiumAmount {
            get {
                return this.accruePremiumAmountField;
            }
            set {
                this.accruePremiumAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://PolicyComponentRead.webservices.gb.com")]
    public partial class ExecuteResponseResponseOutGroupRowOutPolicyTax {
        
        private decimal taxAmountField;
        
        /// <remarks/>
        public decimal TaxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://PolicyComponentRead.webservices.gb.com")]
    public partial class ExecuteResponseResponseOutGroupRowOutIir1PolicyCommission {
        
        private decimal commissionAmountField;
        
        /// <remarks/>
        public decimal CommissionAmount {
            get {
                return this.commissionAmountField;
            }
            set {
                this.commissionAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://PolicyComponentRead.webservices.gb.com")]
    public partial class ExecuteResponseResponseOutGroupRowOutGrossPolicySumInsured {
        
        private decimal accruePremiumAmountField;
        
        /// <remarks/>
        public decimal AccruePremiumAmount {
            get {
                return this.accruePremiumAmountField;
            }
            set {
                this.accruePremiumAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ExecuteCompletedEventHandler(object sender, ExecuteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExecuteResponseResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExecuteResponseResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591