//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Neosinerji.BABOnlineTP.Business.AXAPoliceBasim {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AxaPoliceBasimSoap", Namespace="http://tempuri.org/")]
    public partial class AxaPoliceBasim : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PoliceBasimOperationCompleted;
        
        private System.Threading.SendOrPostCallback DenizBankPoliceBasimOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AxaPoliceBasim() {
            this.Url = global::Neosinerji.BABOnlineTP.Business.Properties.Settings.Default.Neosinerji_BABOnlineTP_Business_AXAPoliceBasim_AxaPoliceBasim;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PoliceBasimCompletedEventHandler PoliceBasimCompleted;
        
        /// <remarks/>
        public event DenizBankPoliceBasimCompletedEventHandler DenizBankPoliceBasimCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PoliceBasim", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AOCPoliceBasimSonuc PoliceBasim(AOCPoliceBasimParametre PoliceBasimParametre) {
            object[] results = this.Invoke("PoliceBasim", new object[] {
                        PoliceBasimParametre});
            return ((AOCPoliceBasimSonuc)(results[0]));
        }
        
        /// <remarks/>
        public void PoliceBasimAsync(AOCPoliceBasimParametre PoliceBasimParametre) {
            this.PoliceBasimAsync(PoliceBasimParametre, null);
        }
        
        /// <remarks/>
        public void PoliceBasimAsync(AOCPoliceBasimParametre PoliceBasimParametre, object userState) {
            if ((this.PoliceBasimOperationCompleted == null)) {
                this.PoliceBasimOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPoliceBasimOperationCompleted);
            }
            this.InvokeAsync("PoliceBasim", new object[] {
                        PoliceBasimParametre}, this.PoliceBasimOperationCompleted, userState);
        }
        
        private void OnPoliceBasimOperationCompleted(object arg) {
            if ((this.PoliceBasimCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PoliceBasimCompleted(this, new PoliceBasimCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DenizBankPoliceBasim", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AOCPoliceBasimSonuc DenizBankPoliceBasim(AOCPoliceBasimParametre PoliceBasimParametre) {
            object[] results = this.Invoke("DenizBankPoliceBasim", new object[] {
                        PoliceBasimParametre});
            return ((AOCPoliceBasimSonuc)(results[0]));
        }
        
        /// <remarks/>
        public void DenizBankPoliceBasimAsync(AOCPoliceBasimParametre PoliceBasimParametre) {
            this.DenizBankPoliceBasimAsync(PoliceBasimParametre, null);
        }
        
        /// <remarks/>
        public void DenizBankPoliceBasimAsync(AOCPoliceBasimParametre PoliceBasimParametre, object userState) {
            if ((this.DenizBankPoliceBasimOperationCompleted == null)) {
                this.DenizBankPoliceBasimOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDenizBankPoliceBasimOperationCompleted);
            }
            this.InvokeAsync("DenizBankPoliceBasim", new object[] {
                        PoliceBasimParametre}, this.DenizBankPoliceBasimOperationCompleted, userState);
        }
        
        private void OnDenizBankPoliceBasimOperationCompleted(object arg) {
            if ((this.DenizBankPoliceBasimCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DenizBankPoliceBasimCompleted(this, new DenizBankPoliceBasimCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AOCPoliceBasimParametre {
        
        private decimal policeNoField;
        
        private decimal zeylSiraNoField;
        
        private string kullaniciField;
        
        private BasimDil dilSecimiField;
        
        private BasimType basimTipiField;
        
        /// <remarks/>
        public decimal PoliceNo {
            get {
                return this.policeNoField;
            }
            set {
                this.policeNoField = value;
            }
        }
        
        /// <remarks/>
        public decimal ZeylSiraNo {
            get {
                return this.zeylSiraNoField;
            }
            set {
                this.zeylSiraNoField = value;
            }
        }
        
        /// <remarks/>
        public string Kullanici {
            get {
                return this.kullaniciField;
            }
            set {
                this.kullaniciField = value;
            }
        }
        
        /// <remarks/>
        public BasimDil DilSecimi {
            get {
                return this.dilSecimiField;
            }
            set {
                this.dilSecimiField = value;
            }
        }
        
        /// <remarks/>
        public BasimType BasimTipi {
            get {
                return this.basimTipiField;
            }
            set {
                this.basimTipiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum BasimDil {
        
        /// <remarks/>
        Turkce,
        
        /// <remarks/>
        Ingilizce,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum BasimType {
        
        /// <remarks/>
        Binary,
        
        /// <remarks/>
        Path,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AOCPoliceBasimSonuc {
        
        private byte[] binaryField;
        
        private string policePathField;
        
        private System.Nullable<decimal> idField;
        
        private string[] hataMesajlariField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Binary {
            get {
                return this.binaryField;
            }
            set {
                this.binaryField = value;
            }
        }
        
        /// <remarks/>
        public string PolicePath {
            get {
                return this.policePathField;
            }
            set {
                this.policePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string[] HataMesajlari {
            get {
                return this.hataMesajlariField;
            }
            set {
                this.hataMesajlariField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PoliceBasimCompletedEventHandler(object sender, PoliceBasimCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PoliceBasimCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PoliceBasimCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AOCPoliceBasimSonuc Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AOCPoliceBasimSonuc)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DenizBankPoliceBasimCompletedEventHandler(object sender, DenizBankPoliceBasimCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DenizBankPoliceBasimCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DenizBankPoliceBasimCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AOCPoliceBasimSonuc Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AOCPoliceBasimSonuc)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591