//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Neosinerji.BABOnlineTP.Business.turknippon.seyahat {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TravelServiceSoap", Namespace="Travel")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SharedOutput))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SharedInput))]
    public partial class TravelService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ComputeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProposalOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveOperationCompleted;
        
        private System.Threading.SendOrPostCallback PrintOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetScopeOrPocketOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCountryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAlternativeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TravelService() {
            this.Url = global::Neosinerji.BABOnlineTP.Business.Properties.Settings.Default.Neosinerji_BABOnlineTP_Business_turknippon_seyahat_TravelService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ComputeCompletedEventHandler ComputeCompleted;
        
        /// <remarks/>
        public event ProposalCompletedEventHandler ProposalCompleted;
        
        /// <remarks/>
        public event ApproveCompletedEventHandler ApproveCompleted;
        
        /// <remarks/>
        public event PrintCompletedEventHandler PrintCompleted;
        
        /// <remarks/>
        public event GetScopeOrPocketCompletedEventHandler GetScopeOrPocketCompleted;
        
        /// <remarks/>
        public event GetCountryCompletedEventHandler GetCountryCompleted;
        
        /// <remarks/>
        public event GetAlternativeCompletedEventHandler GetAlternativeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Travel/Compute", RequestNamespace="Travel", ResponseNamespace="Travel", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TravelOutput Compute(TravelInput Input) {
            object[] results = this.Invoke("Compute", new object[] {
                        Input});
            return ((TravelOutput)(results[0]));
        }
        
        /// <remarks/>
        public void ComputeAsync(TravelInput Input) {
            this.ComputeAsync(Input, null);
        }
        
        /// <remarks/>
        public void ComputeAsync(TravelInput Input, object userState) {
            if ((this.ComputeOperationCompleted == null)) {
                this.ComputeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnComputeOperationCompleted);
            }
            this.InvokeAsync("Compute", new object[] {
                        Input}, this.ComputeOperationCompleted, userState);
        }
        
        private void OnComputeOperationCompleted(object arg) {
            if ((this.ComputeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ComputeCompleted(this, new ComputeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Travel/Proposal", RequestNamespace="Travel", ResponseNamespace="Travel", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TravelOutput Proposal(TravelInput Input) {
            object[] results = this.Invoke("Proposal", new object[] {
                        Input});
            return ((TravelOutput)(results[0]));
        }
        
        /// <remarks/>
        public void ProposalAsync(TravelInput Input) {
            this.ProposalAsync(Input, null);
        }
        
        /// <remarks/>
        public void ProposalAsync(TravelInput Input, object userState) {
            if ((this.ProposalOperationCompleted == null)) {
                this.ProposalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProposalOperationCompleted);
            }
            this.InvokeAsync("Proposal", new object[] {
                        Input}, this.ProposalOperationCompleted, userState);
        }
        
        private void OnProposalOperationCompleted(object arg) {
            if ((this.ProposalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProposalCompleted(this, new ProposalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Travel/Approve", RequestNamespace="Travel", ResponseNamespace="Travel", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TravelOutput Approve(TravelInput Input) {
            object[] results = this.Invoke("Approve", new object[] {
                        Input});
            return ((TravelOutput)(results[0]));
        }
        
        /// <remarks/>
        public void ApproveAsync(TravelInput Input) {
            this.ApproveAsync(Input, null);
        }
        
        /// <remarks/>
        public void ApproveAsync(TravelInput Input, object userState) {
            if ((this.ApproveOperationCompleted == null)) {
                this.ApproveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveOperationCompleted);
            }
            this.InvokeAsync("Approve", new object[] {
                        Input}, this.ApproveOperationCompleted, userState);
        }
        
        private void OnApproveOperationCompleted(object arg) {
            if ((this.ApproveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveCompleted(this, new ApproveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Travel/Print", RequestNamespace="Travel", ResponseNamespace="Travel", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TravelOutput Print(TravelInput Input) {
            object[] results = this.Invoke("Print", new object[] {
                        Input});
            return ((TravelOutput)(results[0]));
        }
        
        /// <remarks/>
        public void PrintAsync(TravelInput Input) {
            this.PrintAsync(Input, null);
        }
        
        /// <remarks/>
        public void PrintAsync(TravelInput Input, object userState) {
            if ((this.PrintOperationCompleted == null)) {
                this.PrintOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrintOperationCompleted);
            }
            this.InvokeAsync("Print", new object[] {
                        Input}, this.PrintOperationCompleted, userState);
        }
        
        private void OnPrintOperationCompleted(object arg) {
            if ((this.PrintCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrintCompleted(this, new PrintCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Travel/GetScopeOrPocket", RequestNamespace="Travel", ResponseNamespace="Travel", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ScopeOutput[] GetScopeOrPocket(bool IsDomestic) {
            object[] results = this.Invoke("GetScopeOrPocket", new object[] {
                        IsDomestic});
            return ((ScopeOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void GetScopeOrPocketAsync(bool IsDomestic) {
            this.GetScopeOrPocketAsync(IsDomestic, null);
        }
        
        /// <remarks/>
        public void GetScopeOrPocketAsync(bool IsDomestic, object userState) {
            if ((this.GetScopeOrPocketOperationCompleted == null)) {
                this.GetScopeOrPocketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetScopeOrPocketOperationCompleted);
            }
            this.InvokeAsync("GetScopeOrPocket", new object[] {
                        IsDomestic}, this.GetScopeOrPocketOperationCompleted, userState);
        }
        
        private void OnGetScopeOrPocketOperationCompleted(object arg) {
            if ((this.GetScopeOrPocketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetScopeOrPocketCompleted(this, new GetScopeOrPocketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Travel/GetCountry", RequestNamespace="Travel", ResponseNamespace="Travel", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CountryOutput[] GetCountry(int Alternative) {
            object[] results = this.Invoke("GetCountry", new object[] {
                        Alternative});
            return ((CountryOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCountryAsync(int Alternative) {
            this.GetCountryAsync(Alternative, null);
        }
        
        /// <remarks/>
        public void GetCountryAsync(int Alternative, object userState) {
            if ((this.GetCountryOperationCompleted == null)) {
                this.GetCountryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCountryOperationCompleted);
            }
            this.InvokeAsync("GetCountry", new object[] {
                        Alternative}, this.GetCountryOperationCompleted, userState);
        }
        
        private void OnGetCountryOperationCompleted(object arg) {
            if ((this.GetCountryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCountryCompleted(this, new GetCountryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Travel/GetAlternative", RequestNamespace="Travel", ResponseNamespace="Travel", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AlternativeOutput[] GetAlternative(bool IsDomestic, int ScopeOrPocket) {
            object[] results = this.Invoke("GetAlternative", new object[] {
                        IsDomestic,
                        ScopeOrPocket});
            return ((AlternativeOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAlternativeAsync(bool IsDomestic, int ScopeOrPocket) {
            this.GetAlternativeAsync(IsDomestic, ScopeOrPocket, null);
        }
        
        /// <remarks/>
        public void GetAlternativeAsync(bool IsDomestic, int ScopeOrPocket, object userState) {
            if ((this.GetAlternativeOperationCompleted == null)) {
                this.GetAlternativeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAlternativeOperationCompleted);
            }
            this.InvokeAsync("GetAlternative", new object[] {
                        IsDomestic,
                        ScopeOrPocket}, this.GetAlternativeOperationCompleted, userState);
        }
        
        private void OnGetAlternativeOperationCompleted(object arg) {
            if ((this.GetAlternativeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAlternativeCompleted(this, new GetAlternativeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Travel")]
    public partial class TravelInput : SharedInput {
        
        private System.Nullable<long> clientNoField;
        
        private string clientCitizenshipNumberField;
        
        private string clientTaxNumberField;
        
        private string phoneNumberField;
        
        private string clientPhoneNumberField;
        
        private string insuredTypeField;
        
        private int nationalityField;
        
        private string passportNumberField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string fatherNameField;
        
        private System.DateTime birthdayField;
        
        private string birthplaceField;
        
        private string genderField;
        
        private string mobilePhoneCountryField;
        
        private string mobilePhoneField;
        
        private System.Nullable<bool> isDomesticField;
        
        private System.Nullable<System.DateTime> beginDateField;
        
        private System.Nullable<System.DateTime> endDateField;
        
        private System.Nullable<int> scopeField;
        
        private System.Nullable<int> travelPocketField;
        
        private System.Nullable<int> alternativeField;
        
        private System.Nullable<int> countryField;
        
        private bool isSkiingField;
        
        private string planCodeField;
        
        private string personalOrParticularField;
        
        private string cancelAlternativeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> ClientNo {
            get {
                return this.clientNoField;
            }
            set {
                this.clientNoField = value;
            }
        }
        
        /// <remarks/>
        public string ClientCitizenshipNumber {
            get {
                return this.clientCitizenshipNumberField;
            }
            set {
                this.clientCitizenshipNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ClientTaxNumber {
            get {
                return this.clientTaxNumberField;
            }
            set {
                this.clientTaxNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ClientPhoneNumber {
            get {
                return this.clientPhoneNumberField;
            }
            set {
                this.clientPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string InsuredType {
            get {
                return this.insuredTypeField;
            }
            set {
                this.insuredTypeField = value;
            }
        }
        
        /// <remarks/>
        public int Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
            }
        }
        
        /// <remarks/>
        public string PassportNumber {
            get {
                return this.passportNumberField;
            }
            set {
                this.passportNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        public string FatherName {
            get {
                return this.fatherNameField;
            }
            set {
                this.fatherNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
            }
        }
        
        /// <remarks/>
        public string Birthplace {
            get {
                return this.birthplaceField;
            }
            set {
                this.birthplaceField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhoneCountry {
            get {
                return this.mobilePhoneCountryField;
            }
            set {
                this.mobilePhoneCountryField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsDomestic {
            get {
                return this.isDomesticField;
            }
            set {
                this.isDomesticField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> BeginDate {
            get {
                return this.beginDateField;
            }
            set {
                this.beginDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Scope {
            get {
                return this.scopeField;
            }
            set {
                this.scopeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TravelPocket {
            get {
                return this.travelPocketField;
            }
            set {
                this.travelPocketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Alternative {
            get {
                return this.alternativeField;
            }
            set {
                this.alternativeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSkiing {
            get {
                return this.isSkiingField;
            }
            set {
                this.isSkiingField = value;
            }
        }
        
        /// <remarks/>
        public string PlanCode {
            get {
                return this.planCodeField;
            }
            set {
                this.planCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PersonalOrParticular {
            get {
                return this.personalOrParticularField;
            }
            set {
                this.personalOrParticularField = value;
            }
        }
        
        /// <remarks/>
        public string CancelAlternative {
            get {
                return this.cancelAlternativeField;
            }
            set {
                this.cancelAlternativeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TravelInput))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Travel")]
    public abstract partial class SharedInput {
        
        private System.Nullable<int> printTypeField;
        
        private System.Nullable<bool> isTestModeField;
        
        private System.Nullable<int> channelField;
        
        private string usernameField;
        
        private string trackingCodeField;
        
        private string citizenshipNumberField;
        
        private string taxNumberField;
        
        private System.Nullable<long> unitNoField;
        
        private System.Nullable<long> policyNoField;
        
        private System.Nullable<int> cashPaymentTypeField;
        
        private System.Nullable<bool> useCreditCardField;
        
        private CreditCardInput creditCardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PrintType {
            get {
                return this.printTypeField;
            }
            set {
                this.printTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsTestMode {
            get {
                return this.isTestModeField;
            }
            set {
                this.isTestModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string TrackingCode {
            get {
                return this.trackingCodeField;
            }
            set {
                this.trackingCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CitizenshipNumber {
            get {
                return this.citizenshipNumberField;
            }
            set {
                this.citizenshipNumberField = value;
            }
        }
        
        /// <remarks/>
        public string TaxNumber {
            get {
                return this.taxNumberField;
            }
            set {
                this.taxNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> UnitNo {
            get {
                return this.unitNoField;
            }
            set {
                this.unitNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> PolicyNo {
            get {
                return this.policyNoField;
            }
            set {
                this.policyNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CashPaymentType {
            get {
                return this.cashPaymentTypeField;
            }
            set {
                this.cashPaymentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> UseCreditCard {
            get {
                return this.useCreditCardField;
            }
            set {
                this.useCreditCardField = value;
            }
        }
        
        /// <remarks/>
        public CreditCardInput CreditCard {
            get {
                return this.creditCardField;
            }
            set {
                this.creditCardField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Travel")]
    public partial class CreditCardInput {
        
        private int cardTypeField;
        
        private string cardNumberField;
        
        private string monthField;
        
        private string yearField;
        
        private string cVVField;
        
        private int installmentField;
        
        private string cardHolderFirstnameField;
        
        private string cardHolderLastnameField;
        
        /// <remarks/>
        public int CardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
            }
        }
        
        /// <remarks/>
        public string Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public string CVV {
            get {
                return this.cVVField;
            }
            set {
                this.cVVField = value;
            }
        }
        
        /// <remarks/>
        public int Installment {
            get {
                return this.installmentField;
            }
            set {
                this.installmentField = value;
            }
        }
        
        /// <remarks/>
        public string CardHolderFirstname {
            get {
                return this.cardHolderFirstnameField;
            }
            set {
                this.cardHolderFirstnameField = value;
            }
        }
        
        /// <remarks/>
        public string CardHolderLastname {
            get {
                return this.cardHolderLastnameField;
            }
            set {
                this.cardHolderLastnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Travel")]
    public partial class AlternativeOutput {
        
        private bool isDomesticField;
        
        private int scopeOrPocketField;
        
        private int alternativeField;
        
        private string titleField;
        
        private string descriptionField;
        
        /// <remarks/>
        public bool IsDomestic {
            get {
                return this.isDomesticField;
            }
            set {
                this.isDomesticField = value;
            }
        }
        
        /// <remarks/>
        public int ScopeOrPocket {
            get {
                return this.scopeOrPocketField;
            }
            set {
                this.scopeOrPocketField = value;
            }
        }
        
        /// <remarks/>
        public int Alternative {
            get {
                return this.alternativeField;
            }
            set {
                this.alternativeField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Travel")]
    public partial class CountryOutput {
        
        private string countryCodeField;
        
        private string countryNameField;
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Travel")]
    public partial class ScopeOutput {
        
        private bool isDomesticField;
        
        private int scopeOrPocketField;
        
        private string titleField;
        
        private string descriptionField;
        
        /// <remarks/>
        public bool IsDomestic {
            get {
                return this.isDomesticField;
            }
            set {
                this.isDomesticField = value;
            }
        }
        
        /// <remarks/>
        public int ScopeOrPocket {
            get {
                return this.scopeOrPocketField;
            }
            set {
                this.scopeOrPocketField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TravelOutput))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Travel")]
    public partial class SharedOutput {
        
        private bool isSuccessField;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        private string trackingCodeField;
        
        private long unitNoField;
        
        private string unitNameField;
        
        private decimal premiumField;
        
        private System.DateTime beginDateField;
        
        private System.DateTime endDateField;
        
        private long policyNoField;
        
        private string printDownloadUrlField;
        
        /// <remarks/>
        public bool IsSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
            }
        }
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string TrackingCode {
            get {
                return this.trackingCodeField;
            }
            set {
                this.trackingCodeField = value;
            }
        }
        
        /// <remarks/>
        public long UnitNo {
            get {
                return this.unitNoField;
            }
            set {
                this.unitNoField = value;
            }
        }
        
        /// <remarks/>
        public string UnitName {
            get {
                return this.unitNameField;
            }
            set {
                this.unitNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal Premium {
            get {
                return this.premiumField;
            }
            set {
                this.premiumField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime BeginDate {
            get {
                return this.beginDateField;
            }
            set {
                this.beginDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public long PolicyNo {
            get {
                return this.policyNoField;
            }
            set {
                this.policyNoField = value;
            }
        }
        
        /// <remarks/>
        public string PrintDownloadUrl {
            get {
                return this.printDownloadUrlField;
            }
            set {
                this.printDownloadUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Travel")]
    public partial class TravelOutput : SharedOutput {
        
        private decimal exchangeRateField;
        
        private long clientNoField;
        
        private TravelInput inputField;
        
        /// <remarks/>
        public decimal ExchangeRate {
            get {
                return this.exchangeRateField;
            }
            set {
                this.exchangeRateField = value;
            }
        }
        
        /// <remarks/>
        public long ClientNo {
            get {
                return this.clientNoField;
            }
            set {
                this.clientNoField = value;
            }
        }
        
        /// <remarks/>
        public TravelInput Input {
            get {
                return this.inputField;
            }
            set {
                this.inputField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ComputeCompletedEventHandler(object sender, ComputeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComputeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ComputeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TravelOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TravelOutput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ProposalCompletedEventHandler(object sender, ProposalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProposalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProposalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TravelOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TravelOutput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ApproveCompletedEventHandler(object sender, ApproveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApproveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApproveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TravelOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TravelOutput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void PrintCompletedEventHandler(object sender, PrintCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrintCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrintCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TravelOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TravelOutput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetScopeOrPocketCompletedEventHandler(object sender, GetScopeOrPocketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetScopeOrPocketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetScopeOrPocketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ScopeOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ScopeOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetCountryCompletedEventHandler(object sender, GetCountryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCountryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCountryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CountryOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CountryOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetAlternativeCompletedEventHandler(object sender, GetAlternativeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAlternativeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAlternativeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AlternativeOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AlternativeOutput[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591