//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Neosinerji.BABOnlineTP.Business.turknippon.dask {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DASKService-v2Soap", Namespace="DASK")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SharedOutput))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SharedInput))]
    public partial class DASKServicev2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ComputeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProposalOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveNoEmuOperationCompleted;
        
        private System.Threading.SendOrPostCallback PrintOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveStatusOperationCompleted;
        
        private AuthHeader authHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetCityListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTownListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMunicipalityListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetQuarterListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStreetListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBuildingListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSectionListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAddressDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBankListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBankBranchListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFinancierListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPolicyDetailXMLOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DASKServicev2() {
            this.Url = global::Neosinerji.BABOnlineTP.Business.Properties.Settings.Default.Neosinerji_BABOnlineTP_Business_turknippon_dask_DASKService_v2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthHeader AuthHeaderValue {
            get {
                return this.authHeaderValueField;
            }
            set {
                this.authHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ComputeCompletedEventHandler ComputeCompleted;
        
        /// <remarks/>
        public event ProposalCompletedEventHandler ProposalCompleted;
        
        /// <remarks/>
        public event ApproveCompletedEventHandler ApproveCompleted;
        
        /// <remarks/>
        public event ApproveNoEmuCompletedEventHandler ApproveNoEmuCompleted;
        
        /// <remarks/>
        public event PrintCompletedEventHandler PrintCompleted;
        
        /// <remarks/>
        public event ApproveStatusCompletedEventHandler ApproveStatusCompleted;
        
        /// <remarks/>
        public event GetCityListCompletedEventHandler GetCityListCompleted;
        
        /// <remarks/>
        public event GetTownListCompletedEventHandler GetTownListCompleted;
        
        /// <remarks/>
        public event GetMunicipalityListCompletedEventHandler GetMunicipalityListCompleted;
        
        /// <remarks/>
        public event GetQuarterListCompletedEventHandler GetQuarterListCompleted;
        
        /// <remarks/>
        public event GetStreetListCompletedEventHandler GetStreetListCompleted;
        
        /// <remarks/>
        public event GetBuildingListCompletedEventHandler GetBuildingListCompleted;
        
        /// <remarks/>
        public event GetSectionListCompletedEventHandler GetSectionListCompleted;
        
        /// <remarks/>
        public event GetAddressDetailCompletedEventHandler GetAddressDetailCompleted;
        
        /// <remarks/>
        public event GetBankListCompletedEventHandler GetBankListCompleted;
        
        /// <remarks/>
        public event GetBankBranchListCompletedEventHandler GetBankBranchListCompleted;
        
        /// <remarks/>
        public event GetFinancierListCompletedEventHandler GetFinancierListCompleted;
        
        /// <remarks/>
        public event GetPolicyDetailXMLCompletedEventHandler GetPolicyDetailXMLCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DASK/Compute", RequestNamespace="DASK", ResponseNamespace="DASK", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DASKOuput Compute(DASKInput Input) {
            object[] results = this.Invoke("Compute", new object[] {
                        Input});
            return ((DASKOuput)(results[0]));
        }
        
        /// <remarks/>
        public void ComputeAsync(DASKInput Input) {
            this.ComputeAsync(Input, null);
        }
        
        /// <remarks/>
        public void ComputeAsync(DASKInput Input, object userState) {
            if ((this.ComputeOperationCompleted == null)) {
                this.ComputeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnComputeOperationCompleted);
            }
            this.InvokeAsync("Compute", new object[] {
                        Input}, this.ComputeOperationCompleted, userState);
        }
        
        private void OnComputeOperationCompleted(object arg) {
            if ((this.ComputeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ComputeCompleted(this, new ComputeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DASK/Proposal", RequestNamespace="DASK", ResponseNamespace="DASK", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DASKOuput Proposal(DASKInput Input) {
            object[] results = this.Invoke("Proposal", new object[] {
                        Input});
            return ((DASKOuput)(results[0]));
        }
        
        /// <remarks/>
        public void ProposalAsync(DASKInput Input) {
            this.ProposalAsync(Input, null);
        }
        
        /// <remarks/>
        public void ProposalAsync(DASKInput Input, object userState) {
            if ((this.ProposalOperationCompleted == null)) {
                this.ProposalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProposalOperationCompleted);
            }
            this.InvokeAsync("Proposal", new object[] {
                        Input}, this.ProposalOperationCompleted, userState);
        }
        
        private void OnProposalOperationCompleted(object arg) {
            if ((this.ProposalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProposalCompleted(this, new ProposalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DASK/Approve", RequestNamespace="DASK", ResponseNamespace="DASK", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DASKOuput Approve(DASKInput Input) {
            object[] results = this.Invoke("Approve", new object[] {
                        Input});
            return ((DASKOuput)(results[0]));
        }
        
        /// <remarks/>
        public void ApproveAsync(DASKInput Input) {
            this.ApproveAsync(Input, null);
        }
        
        /// <remarks/>
        public void ApproveAsync(DASKInput Input, object userState) {
            if ((this.ApproveOperationCompleted == null)) {
                this.ApproveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveOperationCompleted);
            }
            this.InvokeAsync("Approve", new object[] {
                        Input}, this.ApproveOperationCompleted, userState);
        }
        
        private void OnApproveOperationCompleted(object arg) {
            if ((this.ApproveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveCompleted(this, new ApproveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DASK/ApproveNoEmu", RequestNamespace="DASK", ResponseNamespace="DASK", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DASKOuput ApproveNoEmu(DASKInput Input) {
            object[] results = this.Invoke("ApproveNoEmu", new object[] {
                        Input});
            return ((DASKOuput)(results[0]));
        }
        
        /// <remarks/>
        public void ApproveNoEmuAsync(DASKInput Input) {
            this.ApproveNoEmuAsync(Input, null);
        }
        
        /// <remarks/>
        public void ApproveNoEmuAsync(DASKInput Input, object userState) {
            if ((this.ApproveNoEmuOperationCompleted == null)) {
                this.ApproveNoEmuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveNoEmuOperationCompleted);
            }
            this.InvokeAsync("ApproveNoEmu", new object[] {
                        Input}, this.ApproveNoEmuOperationCompleted, userState);
        }
        
        private void OnApproveNoEmuOperationCompleted(object arg) {
            if ((this.ApproveNoEmuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveNoEmuCompleted(this, new ApproveNoEmuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DASK/Print", RequestNamespace="DASK", ResponseNamespace="DASK", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DASKOuput Print(DASKInput Input) {
            object[] results = this.Invoke("Print", new object[] {
                        Input});
            return ((DASKOuput)(results[0]));
        }
        
        /// <remarks/>
        public void PrintAsync(DASKInput Input) {
            this.PrintAsync(Input, null);
        }
        
        /// <remarks/>
        public void PrintAsync(DASKInput Input, object userState) {
            if ((this.PrintOperationCompleted == null)) {
                this.PrintOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrintOperationCompleted);
            }
            this.InvokeAsync("Print", new object[] {
                        Input}, this.PrintOperationCompleted, userState);
        }
        
        private void OnPrintOperationCompleted(object arg) {
            if ((this.PrintCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrintCompleted(this, new PrintCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DASK/ApproveStatus", RequestNamespace="DASK", ResponseNamespace="DASK", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DASKOuput ApproveStatus(DASKInput Input) {
            object[] results = this.Invoke("ApproveStatus", new object[] {
                        Input});
            return ((DASKOuput)(results[0]));
        }
        
        /// <remarks/>
        public void ApproveStatusAsync(DASKInput Input) {
            this.ApproveStatusAsync(Input, null);
        }
        
        /// <remarks/>
        public void ApproveStatusAsync(DASKInput Input, object userState) {
            if ((this.ApproveStatusOperationCompleted == null)) {
                this.ApproveStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveStatusOperationCompleted);
            }
            this.InvokeAsync("ApproveStatus", new object[] {
                        Input}, this.ApproveStatusOperationCompleted, userState);
        }
        
        private void OnApproveStatusOperationCompleted(object arg) {
            if ((this.ApproveStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveStatusCompleted(this, new ApproveStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DASK/GetCityList", RequestNamespace="DASK", ResponseNamespace="DASK", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListOutput[] GetCityList() {
            object[] results = this.Invoke("GetCityList", new object[0]);
            return ((ListOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCityListAsync() {
            this.GetCityListAsync(null);
        }
        
        /// <remarks/>
        public void GetCityListAsync(object userState) {
            if ((this.GetCityListOperationCompleted == null)) {
                this.GetCityListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCityListOperationCompleted);
            }
            this.InvokeAsync("GetCityList", new object[0], this.GetCityListOperationCompleted, userState);
        }
        
        private void OnGetCityListOperationCompleted(object arg) {
            if ((this.GetCityListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCityListCompleted(this, new GetCityListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DASK/GetTownList", RequestNamespace="DASK", ResponseNamespace="DASK", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListOutput[] GetTownList(int citycode) {
            object[] results = this.Invoke("GetTownList", new object[] {
                        citycode});
            return ((ListOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTownListAsync(int citycode) {
            this.GetTownListAsync(citycode, null);
        }
        
        /// <remarks/>
        public void GetTownListAsync(int citycode, object userState) {
            if ((this.GetTownListOperationCompleted == null)) {
                this.GetTownListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTownListOperationCompleted);
            }
            this.InvokeAsync("GetTownList", new object[] {
                        citycode}, this.GetTownListOperationCompleted, userState);
        }
        
        private void OnGetTownListOperationCompleted(object arg) {
            if ((this.GetTownListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTownListCompleted(this, new GetTownListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DASK/GetMunicipalityList", RequestNamespace="DASK", ResponseNamespace="DASK", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListOutput[] GetMunicipalityList(int towncode) {
            object[] results = this.Invoke("GetMunicipalityList", new object[] {
                        towncode});
            return ((ListOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMunicipalityListAsync(int towncode) {
            this.GetMunicipalityListAsync(towncode, null);
        }
        
        /// <remarks/>
        public void GetMunicipalityListAsync(int towncode, object userState) {
            if ((this.GetMunicipalityListOperationCompleted == null)) {
                this.GetMunicipalityListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMunicipalityListOperationCompleted);
            }
            this.InvokeAsync("GetMunicipalityList", new object[] {
                        towncode}, this.GetMunicipalityListOperationCompleted, userState);
        }
        
        private void OnGetMunicipalityListOperationCompleted(object arg) {
            if ((this.GetMunicipalityListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMunicipalityListCompleted(this, new GetMunicipalityListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DASK/GetQuarterList", RequestNamespace="DASK", ResponseNamespace="DASK", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListOutput[] GetQuarterList(int muncode) {
            object[] results = this.Invoke("GetQuarterList", new object[] {
                        muncode});
            return ((ListOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void GetQuarterListAsync(int muncode) {
            this.GetQuarterListAsync(muncode, null);
        }
        
        /// <remarks/>
        public void GetQuarterListAsync(int muncode, object userState) {
            if ((this.GetQuarterListOperationCompleted == null)) {
                this.GetQuarterListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetQuarterListOperationCompleted);
            }
            this.InvokeAsync("GetQuarterList", new object[] {
                        muncode}, this.GetQuarterListOperationCompleted, userState);
        }
        
        private void OnGetQuarterListOperationCompleted(object arg) {
            if ((this.GetQuarterListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetQuarterListCompleted(this, new GetQuarterListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DASK/GetStreetList", RequestNamespace="DASK", ResponseNamespace="DASK", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListOutput[] GetStreetList(int quartercode) {
            object[] results = this.Invoke("GetStreetList", new object[] {
                        quartercode});
            return ((ListOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStreetListAsync(int quartercode) {
            this.GetStreetListAsync(quartercode, null);
        }
        
        /// <remarks/>
        public void GetStreetListAsync(int quartercode, object userState) {
            if ((this.GetStreetListOperationCompleted == null)) {
                this.GetStreetListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStreetListOperationCompleted);
            }
            this.InvokeAsync("GetStreetList", new object[] {
                        quartercode}, this.GetStreetListOperationCompleted, userState);
        }
        
        private void OnGetStreetListOperationCompleted(object arg) {
            if ((this.GetStreetListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStreetListCompleted(this, new GetStreetListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DASK/GetBuildingList", RequestNamespace="DASK", ResponseNamespace="DASK", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListOutput[] GetBuildingList(int streetcode) {
            object[] results = this.Invoke("GetBuildingList", new object[] {
                        streetcode});
            return ((ListOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBuildingListAsync(int streetcode) {
            this.GetBuildingListAsync(streetcode, null);
        }
        
        /// <remarks/>
        public void GetBuildingListAsync(int streetcode, object userState) {
            if ((this.GetBuildingListOperationCompleted == null)) {
                this.GetBuildingListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBuildingListOperationCompleted);
            }
            this.InvokeAsync("GetBuildingList", new object[] {
                        streetcode}, this.GetBuildingListOperationCompleted, userState);
        }
        
        private void OnGetBuildingListOperationCompleted(object arg) {
            if ((this.GetBuildingListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBuildingListCompleted(this, new GetBuildingListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DASK/GetSectionList", RequestNamespace="DASK", ResponseNamespace="DASK", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListOutput[] GetSectionList(long buildingcode) {
            object[] results = this.Invoke("GetSectionList", new object[] {
                        buildingcode});
            return ((ListOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSectionListAsync(long buildingcode) {
            this.GetSectionListAsync(buildingcode, null);
        }
        
        /// <remarks/>
        public void GetSectionListAsync(long buildingcode, object userState) {
            if ((this.GetSectionListOperationCompleted == null)) {
                this.GetSectionListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSectionListOperationCompleted);
            }
            this.InvokeAsync("GetSectionList", new object[] {
                        buildingcode}, this.GetSectionListOperationCompleted, userState);
        }
        
        private void OnGetSectionListOperationCompleted(object arg) {
            if ((this.GetSectionListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSectionListCompleted(this, new GetSectionListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DASK/GetAddressDetail", RequestNamespace="DASK", ResponseNamespace="DASK", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public JetSatisAddressModel GetAddressDetail(long addresscode) {
            object[] results = this.Invoke("GetAddressDetail", new object[] {
                        addresscode});
            return ((JetSatisAddressModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetAddressDetailAsync(long addresscode) {
            this.GetAddressDetailAsync(addresscode, null);
        }
        
        /// <remarks/>
        public void GetAddressDetailAsync(long addresscode, object userState) {
            if ((this.GetAddressDetailOperationCompleted == null)) {
                this.GetAddressDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAddressDetailOperationCompleted);
            }
            this.InvokeAsync("GetAddressDetail", new object[] {
                        addresscode}, this.GetAddressDetailOperationCompleted, userState);
        }
        
        private void OnGetAddressDetailOperationCompleted(object arg) {
            if ((this.GetAddressDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAddressDetailCompleted(this, new GetAddressDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DASK/GetBankList", RequestNamespace="DASK", ResponseNamespace="DASK", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListOutput[] GetBankList() {
            object[] results = this.Invoke("GetBankList", new object[0]);
            return ((ListOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBankListAsync() {
            this.GetBankListAsync(null);
        }
        
        /// <remarks/>
        public void GetBankListAsync(object userState) {
            if ((this.GetBankListOperationCompleted == null)) {
                this.GetBankListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBankListOperationCompleted);
            }
            this.InvokeAsync("GetBankList", new object[0], this.GetBankListOperationCompleted, userState);
        }
        
        private void OnGetBankListOperationCompleted(object arg) {
            if ((this.GetBankListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBankListCompleted(this, new GetBankListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DASK/GetBankBranchList", RequestNamespace="DASK", ResponseNamespace="DASK", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListOutput[] GetBankBranchList(string BankCode) {
            object[] results = this.Invoke("GetBankBranchList", new object[] {
                        BankCode});
            return ((ListOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBankBranchListAsync(string BankCode) {
            this.GetBankBranchListAsync(BankCode, null);
        }
        
        /// <remarks/>
        public void GetBankBranchListAsync(string BankCode, object userState) {
            if ((this.GetBankBranchListOperationCompleted == null)) {
                this.GetBankBranchListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBankBranchListOperationCompleted);
            }
            this.InvokeAsync("GetBankBranchList", new object[] {
                        BankCode}, this.GetBankBranchListOperationCompleted, userState);
        }
        
        private void OnGetBankBranchListOperationCompleted(object arg) {
            if ((this.GetBankBranchListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBankBranchListCompleted(this, new GetBankBranchListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DASK/GetFinancierList", RequestNamespace="DASK", ResponseNamespace="DASK", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListOutput[] GetFinancierList() {
            object[] results = this.Invoke("GetFinancierList", new object[0]);
            return ((ListOutput[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFinancierListAsync() {
            this.GetFinancierListAsync(null);
        }
        
        /// <remarks/>
        public void GetFinancierListAsync(object userState) {
            if ((this.GetFinancierListOperationCompleted == null)) {
                this.GetFinancierListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFinancierListOperationCompleted);
            }
            this.InvokeAsync("GetFinancierList", new object[0], this.GetFinancierListOperationCompleted, userState);
        }
        
        private void OnGetFinancierListOperationCompleted(object arg) {
            if ((this.GetFinancierListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFinancierListCompleted(this, new GetFinancierListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("DASK/GetPolicyDetailXML", RequestNamespace="DASK", ResponseNamespace="DASK", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPolicyDetailXML(long policyno, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> renewal, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> endors, bool testmode) {
            object[] results = this.Invoke("GetPolicyDetailXML", new object[] {
                        policyno,
                        renewal,
                        endors,
                        testmode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPolicyDetailXMLAsync(long policyno, System.Nullable<int> renewal, System.Nullable<int> endors, bool testmode) {
            this.GetPolicyDetailXMLAsync(policyno, renewal, endors, testmode, null);
        }
        
        /// <remarks/>
        public void GetPolicyDetailXMLAsync(long policyno, System.Nullable<int> renewal, System.Nullable<int> endors, bool testmode, object userState) {
            if ((this.GetPolicyDetailXMLOperationCompleted == null)) {
                this.GetPolicyDetailXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPolicyDetailXMLOperationCompleted);
            }
            this.InvokeAsync("GetPolicyDetailXML", new object[] {
                        policyno,
                        renewal,
                        endors,
                        testmode}, this.GetPolicyDetailXMLOperationCompleted, userState);
        }
        
        private void OnGetPolicyDetailXMLOperationCompleted(object arg) {
            if ((this.GetPolicyDetailXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPolicyDetailXMLCompleted(this, new GetPolicyDetailXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DASK")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="DASK", IsNullable=false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string channelField;
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DASK")]
    public partial class ListOutput {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DASK")]
    public partial class JetSatisAddressModel {
        
        private int iL_CODEField;
        
        private string ilField;
        
        private int iC_CODEField;
        
        private string icField;
        
        private long bE_CODEField;
        
        private string beField;
        
        private string smField;
        
        private int mH_CODEField;
        
        private string mhField;
        
        private int cS_CODEField;
        
        private string cdField;
        
        private string skField;
        
        private string stField;
        
        private string apField;
        
        private long bN_CODEField;
        
        private string bnField;
        
        private string bkField;
        
        private string drField;
        
        private string ktField;
        
        private string pkField;
        
        private string bbField;
        
        private string adField;
        
        private string pfField;
        
        private string prField;
        
        private string syField;
        
        private string tlField;
        
        private string akField;
        
        /// <remarks/>
        public int IL_CODE {
            get {
                return this.iL_CODEField;
            }
            set {
                this.iL_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string IL {
            get {
                return this.ilField;
            }
            set {
                this.ilField = value;
            }
        }
        
        /// <remarks/>
        public int IC_CODE {
            get {
                return this.iC_CODEField;
            }
            set {
                this.iC_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string IC {
            get {
                return this.icField;
            }
            set {
                this.icField = value;
            }
        }
        
        /// <remarks/>
        public long BE_CODE {
            get {
                return this.bE_CODEField;
            }
            set {
                this.bE_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string BE {
            get {
                return this.beField;
            }
            set {
                this.beField = value;
            }
        }
        
        /// <remarks/>
        public string SM {
            get {
                return this.smField;
            }
            set {
                this.smField = value;
            }
        }
        
        /// <remarks/>
        public int MH_CODE {
            get {
                return this.mH_CODEField;
            }
            set {
                this.mH_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string MH {
            get {
                return this.mhField;
            }
            set {
                this.mhField = value;
            }
        }
        
        /// <remarks/>
        public int CS_CODE {
            get {
                return this.cS_CODEField;
            }
            set {
                this.cS_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string CD {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
        
        /// <remarks/>
        public string SK {
            get {
                return this.skField;
            }
            set {
                this.skField = value;
            }
        }
        
        /// <remarks/>
        public string ST {
            get {
                return this.stField;
            }
            set {
                this.stField = value;
            }
        }
        
        /// <remarks/>
        public string AP {
            get {
                return this.apField;
            }
            set {
                this.apField = value;
            }
        }
        
        /// <remarks/>
        public long BN_CODE {
            get {
                return this.bN_CODEField;
            }
            set {
                this.bN_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string BN {
            get {
                return this.bnField;
            }
            set {
                this.bnField = value;
            }
        }
        
        /// <remarks/>
        public string BK {
            get {
                return this.bkField;
            }
            set {
                this.bkField = value;
            }
        }
        
        /// <remarks/>
        public string DR {
            get {
                return this.drField;
            }
            set {
                this.drField = value;
            }
        }
        
        /// <remarks/>
        public string KT {
            get {
                return this.ktField;
            }
            set {
                this.ktField = value;
            }
        }
        
        /// <remarks/>
        public string PK {
            get {
                return this.pkField;
            }
            set {
                this.pkField = value;
            }
        }
        
        /// <remarks/>
        public string BB {
            get {
                return this.bbField;
            }
            set {
                this.bbField = value;
            }
        }
        
        /// <remarks/>
        public string AD {
            get {
                return this.adField;
            }
            set {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        public string PF {
            get {
                return this.pfField;
            }
            set {
                this.pfField = value;
            }
        }
        
        /// <remarks/>
        public string PR {
            get {
                return this.prField;
            }
            set {
                this.prField = value;
            }
        }
        
        /// <remarks/>
        public string SY {
            get {
                return this.syField;
            }
            set {
                this.syField = value;
            }
        }
        
        /// <remarks/>
        public string TL {
            get {
                return this.tlField;
            }
            set {
                this.tlField = value;
            }
        }
        
        /// <remarks/>
        public string AK {
            get {
                return this.akField;
            }
            set {
                this.akField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DASKOuput))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DASK")]
    public partial class SharedOutput {
        
        private bool isSuccessField;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        private string trackingCodeField;
        
        private long unitNoField;
        
        private string unitNameField;
        
        private decimal premiumField;
        
        private System.DateTime beginDateField;
        
        private System.DateTime endDateField;
        
        private long policyNoField;
        
        private string printDownloadUrlField;
        
        /// <remarks/>
        public bool IsSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
            }
        }
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string TrackingCode {
            get {
                return this.trackingCodeField;
            }
            set {
                this.trackingCodeField = value;
            }
        }
        
        /// <remarks/>
        public long UnitNo {
            get {
                return this.unitNoField;
            }
            set {
                this.unitNoField = value;
            }
        }
        
        /// <remarks/>
        public string UnitName {
            get {
                return this.unitNameField;
            }
            set {
                this.unitNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal Premium {
            get {
                return this.premiumField;
            }
            set {
                this.premiumField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime BeginDate {
            get {
                return this.beginDateField;
            }
            set {
                this.beginDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public long PolicyNo {
            get {
                return this.policyNoField;
            }
            set {
                this.policyNoField = value;
            }
        }
        
        /// <remarks/>
        public string PrintDownloadUrl {
            get {
                return this.printDownloadUrlField;
            }
            set {
                this.printDownloadUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DASK")]
    public partial class DASKOuput : SharedOutput {
        
        private long clientNoField;
        
        private decimal dASKInsuranceAmountField;
        
        private DASKInput inputField;
        
        private JetSatisAddressModel invalidatedRiskAddressField;
        
        private string dASKWarningField;
        
        private string externalPolicyNoField;
        
        private string extraXmlStringField;
        
        /// <remarks/>
        public long ClientNo {
            get {
                return this.clientNoField;
            }
            set {
                this.clientNoField = value;
            }
        }
        
        /// <remarks/>
        public decimal DASKInsuranceAmount {
            get {
                return this.dASKInsuranceAmountField;
            }
            set {
                this.dASKInsuranceAmountField = value;
            }
        }
        
        /// <remarks/>
        public DASKInput Input {
            get {
                return this.inputField;
            }
            set {
                this.inputField = value;
            }
        }
        
        /// <remarks/>
        public JetSatisAddressModel InvalidatedRiskAddress {
            get {
                return this.invalidatedRiskAddressField;
            }
            set {
                this.invalidatedRiskAddressField = value;
            }
        }
        
        /// <remarks/>
        public string DASKWarning {
            get {
                return this.dASKWarningField;
            }
            set {
                this.dASKWarningField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalPolicyNo {
            get {
                return this.externalPolicyNoField;
            }
            set {
                this.externalPolicyNoField = value;
            }
        }
        
        /// <remarks/>
        public string ExtraXmlString {
            get {
                return this.extraXmlStringField;
            }
            set {
                this.extraXmlStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DASK")]
    public partial class DASKInput : SharedInput {
        
        private System.Nullable<long> clientNoField;
        
        private string clientCitizenshipNumberField;
        
        private string clientTaxNumberField;
        
        private bool isRenewalField;
        
        private System.DateTime beginDateField;
        
        private System.Nullable<long> dASKPolicyNoField;
        
        private System.Nullable<int> insurerTypeField;
        
        private string mobilePhoneNumberField;
        
        private string phoneNumberField;
        
        private string clientMobilePhoneNumberField;
        
        private string clientPhoneNumberField;
        
        private string riskAddressCodeField;
        
        private TitleDeedModel titleDeedField;
        
        private System.Nullable<int> grossAreaM2Field;
        
        private System.Nullable<int> usageTypeField;
        
        private System.Nullable<int> buildTypeField;
        
        private System.Nullable<int> buildYearField;
        
        private System.Nullable<int> totalFloorField;
        
        private System.Nullable<int> anteriorDamageField;
        
        private string lossPayeeTypeField;
        
        private string bankField;
        
        private string bankBranchField;
        
        private string financialInstitutionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> ClientNo {
            get {
                return this.clientNoField;
            }
            set {
                this.clientNoField = value;
            }
        }
        
        /// <remarks/>
        public string ClientCitizenshipNumber {
            get {
                return this.clientCitizenshipNumberField;
            }
            set {
                this.clientCitizenshipNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ClientTaxNumber {
            get {
                return this.clientTaxNumberField;
            }
            set {
                this.clientTaxNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool IsRenewal {
            get {
                return this.isRenewalField;
            }
            set {
                this.isRenewalField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime BeginDate {
            get {
                return this.beginDateField;
            }
            set {
                this.beginDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> DASKPolicyNo {
            get {
                return this.dASKPolicyNoField;
            }
            set {
                this.dASKPolicyNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> InsurerType {
            get {
                return this.insurerTypeField;
            }
            set {
                this.insurerTypeField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhoneNumber {
            get {
                return this.mobilePhoneNumberField;
            }
            set {
                this.mobilePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ClientMobilePhoneNumber {
            get {
                return this.clientMobilePhoneNumberField;
            }
            set {
                this.clientMobilePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ClientPhoneNumber {
            get {
                return this.clientPhoneNumberField;
            }
            set {
                this.clientPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string RiskAddressCode {
            get {
                return this.riskAddressCodeField;
            }
            set {
                this.riskAddressCodeField = value;
            }
        }
        
        /// <remarks/>
        public TitleDeedModel TitleDeed {
            get {
                return this.titleDeedField;
            }
            set {
                this.titleDeedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> GrossAreaM2 {
            get {
                return this.grossAreaM2Field;
            }
            set {
                this.grossAreaM2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> UsageType {
            get {
                return this.usageTypeField;
            }
            set {
                this.usageTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BuildType {
            get {
                return this.buildTypeField;
            }
            set {
                this.buildTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BuildYear {
            get {
                return this.buildYearField;
            }
            set {
                this.buildYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TotalFloor {
            get {
                return this.totalFloorField;
            }
            set {
                this.totalFloorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> AnteriorDamage {
            get {
                return this.anteriorDamageField;
            }
            set {
                this.anteriorDamageField = value;
            }
        }
        
        /// <remarks/>
        public string LossPayeeType {
            get {
                return this.lossPayeeTypeField;
            }
            set {
                this.lossPayeeTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Bank {
            get {
                return this.bankField;
            }
            set {
                this.bankField = value;
            }
        }
        
        /// <remarks/>
        public string BankBranch {
            get {
                return this.bankBranchField;
            }
            set {
                this.bankBranchField = value;
            }
        }
        
        /// <remarks/>
        public string FinancialInstitution {
            get {
                return this.financialInstitutionField;
            }
            set {
                this.financialInstitutionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DASK")]
    public partial class TitleDeedModel {
        
        private string bbField;
        
        private string adField;
        
        private string pfField;
        
        private string prField;
        
        private string syField;
        
        /// <remarks/>
        public string BB {
            get {
                return this.bbField;
            }
            set {
                this.bbField = value;
            }
        }
        
        /// <remarks/>
        public string AD {
            get {
                return this.adField;
            }
            set {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        public string PF {
            get {
                return this.pfField;
            }
            set {
                this.pfField = value;
            }
        }
        
        /// <remarks/>
        public string PR {
            get {
                return this.prField;
            }
            set {
                this.prField = value;
            }
        }
        
        /// <remarks/>
        public string SY {
            get {
                return this.syField;
            }
            set {
                this.syField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DASKInput))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DASK")]
    public abstract partial class SharedInput {
        
        private System.Nullable<int> printTypeField;
        
        private System.Nullable<bool> isTestModeField;
        
        private System.Nullable<int> channelField;
        
        private string usernameField;
        
        private string trackingCodeField;
        
        private string citizenshipNumberField;
        
        private string taxNumberField;
        
        private System.Nullable<long> unitNoField;
        
        private System.Nullable<long> policyNoField;
        
        private System.Nullable<int> cashPaymentTypeField;
        
        private System.Nullable<bool> useCreditCardField;
        
        private CreditCardInput creditCardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PrintType {
            get {
                return this.printTypeField;
            }
            set {
                this.printTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsTestMode {
            get {
                return this.isTestModeField;
            }
            set {
                this.isTestModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string TrackingCode {
            get {
                return this.trackingCodeField;
            }
            set {
                this.trackingCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CitizenshipNumber {
            get {
                return this.citizenshipNumberField;
            }
            set {
                this.citizenshipNumberField = value;
            }
        }
        
        /// <remarks/>
        public string TaxNumber {
            get {
                return this.taxNumberField;
            }
            set {
                this.taxNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> UnitNo {
            get {
                return this.unitNoField;
            }
            set {
                this.unitNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> PolicyNo {
            get {
                return this.policyNoField;
            }
            set {
                this.policyNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CashPaymentType {
            get {
                return this.cashPaymentTypeField;
            }
            set {
                this.cashPaymentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> UseCreditCard {
            get {
                return this.useCreditCardField;
            }
            set {
                this.useCreditCardField = value;
            }
        }
        
        /// <remarks/>
        public CreditCardInput CreditCard {
            get {
                return this.creditCardField;
            }
            set {
                this.creditCardField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="DASK")]
    public partial class CreditCardInput {
        
        private int cardTypeField;
        
        private string cardNumberField;
        
        private string monthField;
        
        private string yearField;
        
        private string cVVField;
        
        private int installmentField;
        
        private string cardHolderFirstnameField;
        
        private string cardHolderLastnameField;
        
        /// <remarks/>
        public int CardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
            }
        }
        
        /// <remarks/>
        public string Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public string CVV {
            get {
                return this.cVVField;
            }
            set {
                this.cVVField = value;
            }
        }
        
        /// <remarks/>
        public int Installment {
            get {
                return this.installmentField;
            }
            set {
                this.installmentField = value;
            }
        }
        
        /// <remarks/>
        public string CardHolderFirstname {
            get {
                return this.cardHolderFirstnameField;
            }
            set {
                this.cardHolderFirstnameField = value;
            }
        }
        
        /// <remarks/>
        public string CardHolderLastname {
            get {
                return this.cardHolderLastnameField;
            }
            set {
                this.cardHolderLastnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ComputeCompletedEventHandler(object sender, ComputeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComputeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ComputeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DASKOuput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DASKOuput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ProposalCompletedEventHandler(object sender, ProposalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProposalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProposalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DASKOuput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DASKOuput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ApproveCompletedEventHandler(object sender, ApproveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApproveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApproveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DASKOuput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DASKOuput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ApproveNoEmuCompletedEventHandler(object sender, ApproveNoEmuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApproveNoEmuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApproveNoEmuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DASKOuput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DASKOuput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void PrintCompletedEventHandler(object sender, PrintCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrintCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrintCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DASKOuput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DASKOuput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ApproveStatusCompletedEventHandler(object sender, ApproveStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApproveStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApproveStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DASKOuput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DASKOuput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetCityListCompletedEventHandler(object sender, GetCityListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCityListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCityListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetTownListCompletedEventHandler(object sender, GetTownListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTownListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTownListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetMunicipalityListCompletedEventHandler(object sender, GetMunicipalityListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMunicipalityListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMunicipalityListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetQuarterListCompletedEventHandler(object sender, GetQuarterListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetQuarterListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetQuarterListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetStreetListCompletedEventHandler(object sender, GetStreetListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStreetListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStreetListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetBuildingListCompletedEventHandler(object sender, GetBuildingListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBuildingListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBuildingListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetSectionListCompletedEventHandler(object sender, GetSectionListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSectionListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSectionListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetAddressDetailCompletedEventHandler(object sender, GetAddressDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAddressDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAddressDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public JetSatisAddressModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((JetSatisAddressModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetBankListCompletedEventHandler(object sender, GetBankListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBankListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBankListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetBankBranchListCompletedEventHandler(object sender, GetBankBranchListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBankBranchListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBankBranchListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetFinancierListCompletedEventHandler(object sender, GetFinancierListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFinancierListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFinancierListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListOutput[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListOutput[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetPolicyDetailXMLCompletedEventHandler(object sender, GetPolicyDetailXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPolicyDetailXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPolicyDetailXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591