//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Neosinerji.BABOnlineTP.Business.sompojapan.common {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CommonSoap", Namespace="http://tempuri.org/")]
    public partial class Common : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private IdentityHeader identityHeaderValueField;
        
        private System.Threading.SendOrPostCallback DecryptTestOperationCompleted;
        
        private System.Threading.SendOrPostCallback OnayOperationCompleted;
        
        private System.Threading.SendOrPostCallback BasimOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Common() {
            this.Url = global::Neosinerji.BABOnlineTP.Business.Properties.Settings.Default.Neosinerji_BABOnlineTP_Business_sompojapan_common_Common;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public IdentityHeader IdentityHeaderValue {
            get {
                return this.identityHeaderValueField;
            }
            set {
                this.identityHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DecryptTestCompletedEventHandler DecryptTestCompleted;
        
        /// <remarks/>
        public event OnayCompletedEventHandler OnayCompleted;
        
        /// <remarks/>
        public event BasimCompletedEventHandler BasimCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("IdentityHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DecryptTest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DecryptTest(string encrypted) {
            object[] results = this.Invoke("DecryptTest", new object[] {
                        encrypted});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DecryptTestAsync(string encrypted) {
            this.DecryptTestAsync(encrypted, null);
        }
        
        /// <remarks/>
        public void DecryptTestAsync(string encrypted, object userState) {
            if ((this.DecryptTestOperationCompleted == null)) {
                this.DecryptTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDecryptTestOperationCompleted);
            }
            this.InvokeAsync("DecryptTest", new object[] {
                        encrypted}, this.DecryptTestOperationCompleted, userState);
        }
        
        private void OnDecryptTestOperationCompleted(object arg) {
            if ((this.DecryptTestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DecryptTestCompleted(this, new DecryptTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("IdentityHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Onay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ConfirmOutput Onay(ExtendConfirmParameters ConfirmParameters) {
            object[] results = this.Invoke("Onay", new object[] {
                        ConfirmParameters});
            return ((ConfirmOutput)(results[0]));
        }
        
        /// <remarks/>
        public void OnayAsync(ExtendConfirmParameters ConfirmParameters) {
            this.OnayAsync(ConfirmParameters, null);
        }
        
        /// <remarks/>
        public void OnayAsync(ExtendConfirmParameters ConfirmParameters, object userState) {
            if ((this.OnayOperationCompleted == null)) {
                this.OnayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOnayOperationCompleted);
            }
            this.InvokeAsync("Onay", new object[] {
                        ConfirmParameters}, this.OnayOperationCompleted, userState);
        }
        
        private void OnOnayOperationCompleted(object arg) {
            if ((this.OnayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OnayCompleted(this, new OnayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("IdentityHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Basim", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("print-response", IsNullable=true)]
        public PrintResponse Basim(Policy policy, PrintoutType documentType) {
            object[] results = this.Invoke("Basim", new object[] {
                        policy,
                        documentType});
            return ((PrintResponse)(results[0]));
        }
        
        /// <remarks/>
        public void BasimAsync(Policy policy, PrintoutType documentType) {
            this.BasimAsync(policy, documentType, null);
        }
        
        /// <remarks/>
        public void BasimAsync(Policy policy, PrintoutType documentType, object userState) {
            if ((this.BasimOperationCompleted == null)) {
                this.BasimOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBasimOperationCompleted);
            }
            this.InvokeAsync("Basim", new object[] {
                        policy,
                        documentType}, this.BasimOperationCompleted, userState);
        }
        
        private void OnBasimOperationCompleted(object arg) {
            if ((this.BasimCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BasimCompleted(this, new BasimCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class IdentityHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string kullaniciAdiField;
        
        private string kullaniciParolaField;
        
        private string kullaniciIPField;
        
        private ClientType kullaniciTipiField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string KullaniciAdi {
            get {
                return this.kullaniciAdiField;
            }
            set {
                this.kullaniciAdiField = value;
            }
        }
        
        /// <remarks/>
        public string KullaniciParola {
            get {
                return this.kullaniciParolaField;
            }
            set {
                this.kullaniciParolaField = value;
            }
        }
        
        /// <remarks/>
        public string KullaniciIP {
            get {
                return this.kullaniciIPField;
            }
            set {
                this.kullaniciIPField = value;
            }
        }
        
        /// <remarks/>
        public ClientType KullaniciTipi {
            get {
                return this.kullaniciTipiField;
            }
            set {
                this.kullaniciTipiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ClientType {
        
        /// <remarks/>
        ACENTE,
        
        /// <remarks/>
        INTERNET,
        
        /// <remarks/>
        DEVELOP,
        
        /// <remarks/>
        INNER_SERVICE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintResponse {
        
        private bool successField;
        
        private string downloadurlField;
        
        private string descriptionField;
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("download-url")]
        public string downloadurl {
            get {
                return this.downloadurlField;
            }
            set {
                this.downloadurlField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InstallmentOfConfirmOutput {
        
        private int iNSTALLMENT_ORDER_NOField;
        
        private decimal iNSTALLMENT_AMOUNTField;
        
        private System.DateTime iNSTALLMENT_DATEField;
        
        /// <remarks/>
        public int INSTALLMENT_ORDER_NO {
            get {
                return this.iNSTALLMENT_ORDER_NOField;
            }
            set {
                this.iNSTALLMENT_ORDER_NOField = value;
            }
        }
        
        /// <remarks/>
        public decimal INSTALLMENT_AMOUNT {
            get {
                return this.iNSTALLMENT_AMOUNTField;
            }
            set {
                this.iNSTALLMENT_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime INSTALLMENT_DATE {
            get {
                return this.iNSTALLMENT_DATEField;
            }
            set {
                this.iNSTALLMENT_DATEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TaxOfConfirmOutput {
        
        private decimal dEDUCTION_AMOUNTField;
        
        private string dEDUCTION_DESCRIPTIONField;
        
        /// <remarks/>
        public decimal DEDUCTION_AMOUNT {
            get {
                return this.dEDUCTION_AMOUNTField;
            }
            set {
                this.dEDUCTION_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        public string DEDUCTION_DESCRIPTION {
            get {
                return this.dEDUCTION_DESCRIPTIONField;
            }
            set {
                this.dEDUCTION_DESCRIPTIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PaymentOfConfirmOutput {
        
        private string pOL_CURRENCY_TYPEField;
        
        private decimal nET_PREMIUMField;
        
        private TaxOfConfirmOutput[] tAXESField;
        
        private decimal gROSS_PREMIUMField;
        
        private InstallmentOfConfirmOutput[] iNSTALLMENTSField;
        
        /// <remarks/>
        public string POL_CURRENCY_TYPE {
            get {
                return this.pOL_CURRENCY_TYPEField;
            }
            set {
                this.pOL_CURRENCY_TYPEField = value;
            }
        }
        
        /// <remarks/>
        public decimal NET_PREMIUM {
            get {
                return this.nET_PREMIUMField;
            }
            set {
                this.nET_PREMIUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TAX")]
        public TaxOfConfirmOutput[] TAXES {
            get {
                return this.tAXESField;
            }
            set {
                this.tAXESField = value;
            }
        }
        
        /// <remarks/>
        public decimal GROSS_PREMIUM {
            get {
                return this.gROSS_PREMIUMField;
            }
            set {
                this.gROSS_PREMIUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INSTALLMENTS")]
        public InstallmentOfConfirmOutput[] INSTALLMENTS {
            get {
                return this.iNSTALLMENTSField;
            }
            set {
                this.iNSTALLMENTSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ErrorOfConfirmOutput {
        
        private int eRROR_CODEField;
        
        private ErrorSourceEnum eRROR_SOURCEField;
        
        private string eRROR_DESCRIPTIONField;
        
        /// <remarks/>
        public int ERROR_CODE {
            get {
                return this.eRROR_CODEField;
            }
            set {
                this.eRROR_CODEField = value;
            }
        }
        
        /// <remarks/>
        public ErrorSourceEnum ERROR_SOURCE {
            get {
                return this.eRROR_SOURCEField;
            }
            set {
                this.eRROR_SOURCEField = value;
            }
        }
        
        /// <remarks/>
        public string ERROR_DESCRIPTION {
            get {
                return this.eRROR_DESCRIPTIONField;
            }
            set {
                this.eRROR_DESCRIPTIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ErrorSourceEnum {
        
        /// <remarks/>
        Core,
        
        /// <remarks/>
        Winsure,
        
        /// <remarks/>
        Inet,
        
        /// <remarks/>
        WebService,
        
        /// <remarks/>
        WinsureAuthorization,
        
        /// <remarks/>
        PrintingService,
        
        /// <remarks/>
        ExternalService,
        
        /// <remarks/>
        Internal,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultOfConfirmOutput {
        
        private int rESULT_CODEField;
        
        private ErrorOfConfirmOutput eRRORField;
        
        /// <remarks/>
        public int RESULT_CODE {
            get {
                return this.rESULT_CODEField;
            }
            set {
                this.rESULT_CODEField = value;
            }
        }
        
        /// <remarks/>
        public ErrorOfConfirmOutput ERROR {
            get {
                return this.eRRORField;
            }
            set {
                this.eRRORField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfirmOutput {
        
        private string rEQUEST_MESSAGE_NOField;
        
        private long rESPONSE_MESSAGE_NOField;
        
        private ResultOfConfirmOutput rESULTField;
        
        private System.Nullable<long> pOLICY_NUMBERField;
        
        private string eXTERNAL_POLICY_NUMBERField;
        
        private PaymentOfConfirmOutput pAYMENTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REQUEST_MESSAGE_NO {
            get {
                return this.rEQUEST_MESSAGE_NOField;
            }
            set {
                this.rEQUEST_MESSAGE_NOField = value;
            }
        }
        
        /// <remarks/>
        public long RESPONSE_MESSAGE_NO {
            get {
                return this.rESPONSE_MESSAGE_NOField;
            }
            set {
                this.rESPONSE_MESSAGE_NOField = value;
            }
        }
        
        /// <remarks/>
        public ResultOfConfirmOutput RESULT {
            get {
                return this.rESULTField;
            }
            set {
                this.rESULTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> POLICY_NUMBER {
            get {
                return this.pOLICY_NUMBERField;
            }
            set {
                this.pOLICY_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EXTERNAL_POLICY_NUMBER {
            get {
                return this.eXTERNAL_POLICY_NUMBERField;
            }
            set {
                this.eXTERNAL_POLICY_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PaymentOfConfirmOutput PAYMENT {
            get {
                return this.pAYMENTField;
            }
            set {
                this.pAYMENTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PaymentInfo {
        
        private int installmentField;
        
        private System.Nullable<int> accountBankNoField;
        
        private System.Nullable<uint> accountBranchCodeField;
        
        private System.Nullable<uint> accountNoField;
        
        private string accountOwnerNameField;
        
        private string creditCardCvvField;
        
        private string creditCardEndYearField;
        
        private string creditCardEndMonthField;
        
        private string creditCardNameSurnameField;
        
        private string creditCardNumberField;
        
        private PaymentMethod paymentTypeField;
        
        /// <remarks/>
        public int Installment {
            get {
                return this.installmentField;
            }
            set {
                this.installmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> AccountBankNo {
            get {
                return this.accountBankNoField;
            }
            set {
                this.accountBankNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<uint> AccountBranchCode {
            get {
                return this.accountBranchCodeField;
            }
            set {
                this.accountBranchCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<uint> AccountNo {
            get {
                return this.accountNoField;
            }
            set {
                this.accountNoField = value;
            }
        }
        
        /// <remarks/>
        public string AccountOwnerName {
            get {
                return this.accountOwnerNameField;
            }
            set {
                this.accountOwnerNameField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCardCvv {
            get {
                return this.creditCardCvvField;
            }
            set {
                this.creditCardCvvField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCardEndYear {
            get {
                return this.creditCardEndYearField;
            }
            set {
                this.creditCardEndYearField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCardEndMonth {
            get {
                return this.creditCardEndMonthField;
            }
            set {
                this.creditCardEndMonthField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCardNameSurname {
            get {
                return this.creditCardNameSurnameField;
            }
            set {
                this.creditCardNameSurnameField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCardNumber {
            get {
                return this.creditCardNumberField;
            }
            set {
                this.creditCardNumberField = value;
            }
        }
        
        /// <remarks/>
        public PaymentMethod PaymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum PaymentMethod {
        
        /// <remarks/>
        WithCreditCard,
        
        /// <remarks/>
        AsCash,
        
        /// <remarks/>
        FromBankAccount,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProposalUpdateUnsAddressEntity {
        
        private string aDR_TYPEField;
        
        private string aDR_DATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ADR_TYPE {
            get {
                return this.aDR_TYPEField;
            }
            set {
                this.aDR_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ADR_DATA {
            get {
                return this.aDR_DATAField;
            }
            set {
                this.aDR_DATAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProposalUpdateUnsMasterEntity {
        
        private string eNTITY_NAMEField;
        
        private string eNTITY_VALUEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ENTITY_NAME {
            get {
                return this.eNTITY_NAMEField;
            }
            set {
                this.eNTITY_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ENTITY_VALUE {
            get {
                return this.eNTITY_VALUEField;
            }
            set {
                this.eNTITY_VALUEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProposalUnitUpdateEntity {
        
        private ProposalUpdateUnsMasterEntity[] uPDATE_UNSMAS_ENTITIESField;
        
        private ProposalUpdateUnsAddressEntity[] uNSADRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("UPDATE_UNSMAS")]
        public ProposalUpdateUnsMasterEntity[] UPDATE_UNSMAS_ENTITIES {
            get {
                return this.uPDATE_UNSMAS_ENTITIESField;
            }
            set {
                this.uPDATE_UNSMAS_ENTITIESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ADDRESS")]
        public ProposalUpdateUnsAddressEntity[] UNSADR {
            get {
                return this.uNSADRField;
            }
            set {
                this.uNSADRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Question {
        
        private System.Nullable<int> qUESTION_CODEField;
        
        private string aNSWERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> QUESTION_CODE {
            get {
                return this.qUESTION_CODEField;
            }
            set {
                this.qUESTION_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ANSWER {
            get {
                return this.aNSWERField;
            }
            set {
                this.aNSWERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Address {
        
        private string aDDRESS_TYPEField;
        
        private string aDDRESS_DATAField;
        
        /// <remarks/>
        public string ADDRESS_TYPE {
            get {
                return this.aDDRESS_TYPEField;
            }
            set {
                this.aDDRESS_TYPEField = value;
            }
        }
        
        /// <remarks/>
        public string ADDRESS_DATA {
            get {
                return this.aDDRESS_DATAField;
            }
            set {
                this.aDDRESS_DATAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Unit {
        
        private System.Nullable<long> iDENTITY_NOField;
        
        private string tAX_NOField;
        
        private string nAMEField;
        
        private string sURNAMEField;
        
        private System.Nullable<System.DateTime> bIRTHDATEField;
        
        private string fIRM_NAMEField;
        
        private string fATHER_NAMEField;
        
        private string mARITAL_STATUSField;
        
        private string bIRTH_PLACEField;
        
        private System.Nullable<short> oCCUPATIONField;
        
        private System.Nullable<short> nATIONALITYField;
        
        private string pERSONAL_COMMERCIALField;
        
        private System.Nullable<short> pHONE_COUNTRY_CODEField;
        
        private System.Nullable<short> pHONE_CODEField;
        
        private System.Nullable<long> pHONE_NUMBERField;
        
        private string eMAIL_ADDRESSField;
        
        private System.Nullable<int> bASE_NOField;
        
        private string gSM_COUNTRY_CODEField;
        
        private string gSM_CODEField;
        
        private string gSM_NUMBERField;
        
        private System.Nullable<short> fAX_COUNTRY_CODEField;
        
        private System.Nullable<short> fAX_CODEField;
        
        private System.Nullable<long> fAX_NUMBERField;
        
        private Address[] aDDRESS_LISTField;
        
        private Question[] qUESTION_LISTField;
        
        private string gENDERField;
        
        private ProposalUnitUpdateEntity uPDATEENTITYField;
        
        private System.Nullable<long> uNIT_NOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IDENTITY_NO {
            get {
                return this.iDENTITY_NOField;
            }
            set {
                this.iDENTITY_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TAX_NO {
            get {
                return this.tAX_NOField;
            }
            set {
                this.tAX_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SURNAME {
            get {
                return this.sURNAMEField;
            }
            set {
                this.sURNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> BIRTHDATE {
            get {
                return this.bIRTHDATEField;
            }
            set {
                this.bIRTHDATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FIRM_NAME {
            get {
                return this.fIRM_NAMEField;
            }
            set {
                this.fIRM_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FATHER_NAME {
            get {
                return this.fATHER_NAMEField;
            }
            set {
                this.fATHER_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MARITAL_STATUS {
            get {
                return this.mARITAL_STATUSField;
            }
            set {
                this.mARITAL_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BIRTH_PLACE {
            get {
                return this.bIRTH_PLACEField;
            }
            set {
                this.bIRTH_PLACEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> OCCUPATION {
            get {
                return this.oCCUPATIONField;
            }
            set {
                this.oCCUPATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> NATIONALITY {
            get {
                return this.nATIONALITYField;
            }
            set {
                this.nATIONALITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PERSONAL_COMMERCIAL {
            get {
                return this.pERSONAL_COMMERCIALField;
            }
            set {
                this.pERSONAL_COMMERCIALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> PHONE_COUNTRY_CODE {
            get {
                return this.pHONE_COUNTRY_CODEField;
            }
            set {
                this.pHONE_COUNTRY_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> PHONE_CODE {
            get {
                return this.pHONE_CODEField;
            }
            set {
                this.pHONE_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> PHONE_NUMBER {
            get {
                return this.pHONE_NUMBERField;
            }
            set {
                this.pHONE_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EMAIL_ADDRESS {
            get {
                return this.eMAIL_ADDRESSField;
            }
            set {
                this.eMAIL_ADDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BASE_NO {
            get {
                return this.bASE_NOField;
            }
            set {
                this.bASE_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GSM_COUNTRY_CODE {
            get {
                return this.gSM_COUNTRY_CODEField;
            }
            set {
                this.gSM_COUNTRY_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GSM_CODE {
            get {
                return this.gSM_CODEField;
            }
            set {
                this.gSM_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GSM_NUMBER {
            get {
                return this.gSM_NUMBERField;
            }
            set {
                this.gSM_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> FAX_COUNTRY_CODE {
            get {
                return this.fAX_COUNTRY_CODEField;
            }
            set {
                this.fAX_COUNTRY_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> FAX_CODE {
            get {
                return this.fAX_CODEField;
            }
            set {
                this.fAX_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> FAX_NUMBER {
            get {
                return this.fAX_NUMBERField;
            }
            set {
                this.fAX_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ADDRESS")]
        public Address[] ADDRESS_LIST {
            get {
                return this.aDDRESS_LISTField;
            }
            set {
                this.aDDRESS_LISTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("QUESTION")]
        public Question[] QUESTION_LIST {
            get {
                return this.qUESTION_LISTField;
            }
            set {
                this.qUESTION_LISTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GENDER {
            get {
                return this.gENDERField;
            }
            set {
                this.gENDERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProposalUnitUpdateEntity UPDATEENTITY {
            get {
                return this.uPDATEENTITYField;
            }
            set {
                this.uPDATEENTITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> UNIT_NO {
            get {
                return this.uNIT_NOField;
            }
            set {
                this.uNIT_NOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomParameter {
        
        private string codeField;
        
        private string valueField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Policy {
        
        private long policyNumberField;
        
        private ProductName productNameField;
        
        private int endorsNrField;
        
        private int renewalNrField;
        
        private int firmCodeField;
        
        private int companyCodeField;
        
        private CustomParameter[] parametersField;
        
        /// <remarks/>
        public long PolicyNumber {
            get {
                return this.policyNumberField;
            }
            set {
                this.policyNumberField = value;
            }
        }
        
        /// <remarks/>
        public ProductName ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        public int EndorsNr {
            get {
                return this.endorsNrField;
            }
            set {
                this.endorsNrField = value;
            }
        }
        
        /// <remarks/>
        public int RenewalNr {
            get {
                return this.renewalNrField;
            }
            set {
                this.renewalNrField = value;
            }
        }
        
        /// <remarks/>
        public int FirmCode {
            get {
                return this.firmCodeField;
            }
            set {
                this.firmCodeField = value;
            }
        }
        
        /// <remarks/>
        public int CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
            }
        }
        
        /// <remarks/>
        public CustomParameter[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ProductName {
        
        /// <remarks/>
        BireyselKasko,
        
        /// <remarks/>
        TicariKasko,
        
        /// <remarks/>
        ZorunluMaliMesuliyet,
        
        /// <remarks/>
        YurticiSeyahat,
        
        /// <remarks/>
        YurtdisiSeyahat,
        
        /// <remarks/>
        ArtiKonut,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExtendConfirmParameters {
        
        private Policy policyField;
        
        private CustomParameter[] parametersField;
        
        private Unit unitField;
        
        private PaymentInfo paymentInputField;
        
        /// <remarks/>
        public Policy Policy {
            get {
                return this.policyField;
            }
            set {
                this.policyField = value;
            }
        }
        
        /// <remarks/>
        public CustomParameter[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        public Unit Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        public PaymentInfo PaymentInput {
            get {
                return this.paymentInputField;
            }
            set {
                this.paymentInputField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum PrintoutType {
        
        /// <remarks/>
        Policy,
        
        /// <remarks/>
        PolicyEn,
        
        /// <remarks/>
        PolicyConsulate,
        
        /// <remarks/>
        CustomerInformationForm,
        
        /// <remarks/>
        Slip,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DecryptTestCompletedEventHandler(object sender, DecryptTestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DecryptTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DecryptTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void OnayCompletedEventHandler(object sender, OnayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OnayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OnayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConfirmOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConfirmOutput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void BasimCompletedEventHandler(object sender, BasimCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BasimCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BasimCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PrintResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PrintResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591